// Code generated by ent, DO NOT EDIT.

package votesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLTE(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldGameID, v))
}

// AccusedPlayerID applies equality check predicate on the "accused_player_id" field. It's identical to AccusedPlayerIDEQ.
func AccusedPlayerID(v uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldAccusedPlayerID, v))
}

// AccusedPlayerName applies equality check predicate on the "accused_player_name" field. It's identical to AccusedPlayerNameEQ.
func AccusedPlayerName(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldAccusedPlayerName, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldMessage, v))
}

// OpenedAt applies equality check predicate on the "opened_at" field. It's identical to OpenedAtEQ.
func OpenedAt(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldOpenedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldClosedAt, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLTE(FieldGameID, v))
}

// GameIDContains applies the Contains predicate on the "game_id" field.
func GameIDContains(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldContains(FieldGameID, v))
}

// GameIDHasPrefix applies the HasPrefix predicate on the "game_id" field.
func GameIDHasPrefix(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldHasPrefix(FieldGameID, v))
}

// GameIDHasSuffix applies the HasSuffix predicate on the "game_id" field.
func GameIDHasSuffix(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldHasSuffix(FieldGameID, v))
}

// GameIDEqualFold applies the EqualFold predicate on the "game_id" field.
func GameIDEqualFold(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEqualFold(FieldGameID, v))
}

// GameIDContainsFold applies the ContainsFold predicate on the "game_id" field.
func GameIDContainsFold(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldContainsFold(FieldGameID, v))
}

// AccusedPlayerIDEQ applies the EQ predicate on the "accused_player_id" field.
func AccusedPlayerIDEQ(v uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldAccusedPlayerID, v))
}

// AccusedPlayerIDNEQ applies the NEQ predicate on the "accused_player_id" field.
func AccusedPlayerIDNEQ(v uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldAccusedPlayerID, v))
}

// AccusedPlayerIDIn applies the In predicate on the "accused_player_id" field.
func AccusedPlayerIDIn(vs ...uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldAccusedPlayerID, vs...))
}

// AccusedPlayerIDNotIn applies the NotIn predicate on the "accused_player_id" field.
func AccusedPlayerIDNotIn(vs ...uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldAccusedPlayerID, vs...))
}

// AccusedPlayerIDGT applies the GT predicate on the "accused_player_id" field.
func AccusedPlayerIDGT(v uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGT(FieldAccusedPlayerID, v))
}

// AccusedPlayerIDGTE applies the GTE predicate on the "accused_player_id" field.
func AccusedPlayerIDGTE(v uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGTE(FieldAccusedPlayerID, v))
}

// AccusedPlayerIDLT applies the LT predicate on the "accused_player_id" field.
func AccusedPlayerIDLT(v uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLT(FieldAccusedPlayerID, v))
}

// AccusedPlayerIDLTE applies the LTE predicate on the "accused_player_id" field.
func AccusedPlayerIDLTE(v uuid.UUID) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLTE(FieldAccusedPlayerID, v))
}

// AccusedPlayerNameEQ applies the EQ predicate on the "accused_player_name" field.
func AccusedPlayerNameEQ(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameNEQ applies the NEQ predicate on the "accused_player_name" field.
func AccusedPlayerNameNEQ(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameIn applies the In predicate on the "accused_player_name" field.
func AccusedPlayerNameIn(vs ...string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldAccusedPlayerName, vs...))
}

// AccusedPlayerNameNotIn applies the NotIn predicate on the "accused_player_name" field.
func AccusedPlayerNameNotIn(vs ...string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldAccusedPlayerName, vs...))
}

// AccusedPlayerNameGT applies the GT predicate on the "accused_player_name" field.
func AccusedPlayerNameGT(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGT(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameGTE applies the GTE predicate on the "accused_player_name" field.
func AccusedPlayerNameGTE(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGTE(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameLT applies the LT predicate on the "accused_player_name" field.
func AccusedPlayerNameLT(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLT(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameLTE applies the LTE predicate on the "accused_player_name" field.
func AccusedPlayerNameLTE(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLTE(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameContains applies the Contains predicate on the "accused_player_name" field.
func AccusedPlayerNameContains(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldContains(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameHasPrefix applies the HasPrefix predicate on the "accused_player_name" field.
func AccusedPlayerNameHasPrefix(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldHasPrefix(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameHasSuffix applies the HasSuffix predicate on the "accused_player_name" field.
func AccusedPlayerNameHasSuffix(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldHasSuffix(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameEqualFold applies the EqualFold predicate on the "accused_player_name" field.
func AccusedPlayerNameEqualFold(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEqualFold(FieldAccusedPlayerName, v))
}

// AccusedPlayerNameContainsFold applies the ContainsFold predicate on the "accused_player_name" field.
func AccusedPlayerNameContainsFold(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldContainsFold(FieldAccusedPlayerName, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldContainsFold(FieldMessage, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldStatus, vs...))
}

// OpenedAtEQ applies the EQ predicate on the "opened_at" field.
func OpenedAtEQ(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldOpenedAt, v))
}

// OpenedAtNEQ applies the NEQ predicate on the "opened_at" field.
func OpenedAtNEQ(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldOpenedAt, v))
}

// OpenedAtIn applies the In predicate on the "opened_at" field.
func OpenedAtIn(vs ...time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldOpenedAt, vs...))
}

// OpenedAtNotIn applies the NotIn predicate on the "opened_at" field.
func OpenedAtNotIn(vs ...time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldOpenedAt, vs...))
}

// OpenedAtGT applies the GT predicate on the "opened_at" field.
func OpenedAtGT(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGT(FieldOpenedAt, v))
}

// OpenedAtGTE applies the GTE predicate on the "opened_at" field.
func OpenedAtGTE(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGTE(FieldOpenedAt, v))
}

// OpenedAtLT applies the LT predicate on the "opened_at" field.
func OpenedAtLT(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLT(FieldOpenedAt, v))
}

// OpenedAtLTE applies the LTE predicate on the "opened_at" field.
func OpenedAtLTE(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLTE(FieldOpenedAt, v))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.VoteSession {
	return predicate.VoteSession(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.VoteSession {
	return predicate.VoteSession(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.VoteSession {
	return predicate.VoteSession(sql.FieldNotNull(FieldClosedAt))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.VoteSession {
	return predicate.VoteSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.VoteSession {
	return predicate.VoteSession(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBallots applies the HasEdge predicate on the "ballots" edge.
func HasBallots() predicate.VoteSession {
	return predicate.VoteSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BallotsTable, BallotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBallotsWith applies the HasEdge predicate on the "ballots" edge with a given conditions (other predicates).
func HasBallotsWith(preds ...predicate.Ballot) predicate.VoteSession {
	return predicate.VoteSession(func(s *sql.Selector) {
		step := newBallotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VoteSession) predicate.VoteSession {
	return predicate.VoteSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VoteSession) predicate.VoteSession {
	return predicate.VoteSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VoteSession) predicate.VoteSession {
	return predicate.VoteSession(sql.NotPredicates(p))
}
