// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// GameRole is the predicate function for gamerole builders.
type GameRole func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleTemplate is the predicate function for roletemplate builders.
type RoleTemplate func(*sql.Selector)

// RoleTemplateRole is the predicate function for roletemplaterole builders.
type RoleTemplateRole func(*sql.Selector)
