/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin login
         * @description Authenticates an admin user and returns a JWT token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials */
            requestBody: {
                content: {
                    "application/json": {
                        password?: string;
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.LoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/role-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List role templates
         * @description Retrieves all role templates. Optionally filter by player_count.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by player count */
                    player_count?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleTemplateResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a role template
         * @description Creates a new role template. Requires admin authentication.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Template data */
            requestBody: {
                content: {
                    "application/json": {
                        description?: string;
                        name?: string;
                        player_count?: number;
                        roles?: Record<string, never>[];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleTemplateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/role-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a role template by ID
         * @description Retrieves a single role template with its role assignments.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Template ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleTemplateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a role template
         * @description Deletes a role template. Requires admin authentication.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Template ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a role template
         * @description Updates an existing role template. Requires admin authentication.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Template ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Partial template data */
            requestBody?: {
                content: {
                    "application/json": {
                        description?: string;
                        name?: string;
                        player_count?: number;
                        roles?: Record<string, never>[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleTemplateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all roles
         * @description Retrieves all available roles in the game.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleResponse"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a role
         * @description Creates a new game role. Requires admin authentication.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Role data */
            requestBody: {
                content: {
                    "application/json": {
                        abilities?: string[];
                        description?: string;
                        name?: string;
                        slug?: string;
                        team?: string;
                        video?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a role
         * @description Deletes a role. Requires admin authentication.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a role
         * @description Updates an existing role. Requires admin authentication.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Partial role data */
            requestBody?: {
                content: {
                    "application/json": {
                        abilities?: string[];
                        description?: string;
                        name?: string;
                        slug?: string;
                        team?: string;
                        video?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List admin users
         * @description Retrieves all admin users. Requires admin authentication.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.AdminResponse"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an admin user
         * @description Creates a new admin user. Requires admin authentication.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Admin data */
            requestBody: {
                content: {
                    "application/json": {
                        email?: string;
                        password?: string;
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.AdminResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an admin user
         * @description Retrieves an admin user by ID. Requires admin authentication.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Admin ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.AdminResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete an admin user
         * @description Deletes an admin user. Requires admin authentication.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Admin ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update an admin user
         * @description Updates an admin user. Requires admin authentication.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Admin ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Partial admin data */
            requestBody?: {
                content: {
                    "application/json": {
                        email?: string;
                        is_active?: boolean;
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.AdminResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/users/{id}/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change admin password
         * @description Changes the password for an admin user. Requires admin authentication.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Admin ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Password change data */
            requestBody: {
                content: {
                    "application/json": {
                        new_password?: string;
                        old_password?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ChangePasswordSuccessResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new game
         * @description Creates a new Mafia game session. The caller becomes the moderator.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Moderator identifier */
                    "X-Moderator-ID": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.GameResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a game by ID
         * @description Retrieves a game by its ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Game ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.GameResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a game
         * @description Deletes a game. Only the moderator can delete.
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description Moderator identifier */
                    "X-Moderator-ID": string;
                };
                path: {
                    /** @description Game ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update game status
         * @description Updates the status of a game. Only the moderator can update.
         */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Moderator identifier */
                    "X-Moderator-ID": string;
                };
                path: {
                    /** @description Game ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description New status */
            requestBody: {
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.GameResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/games/{id}/distribute-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Distribute roles to players
         * @description Randomly assigns roles to all players. Only the moderator can trigger this.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Moderator identifier */
                    "X-Moderator-ID": string;
                };
                path: {
                    /** @description Game ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Role selections */
            requestBody: {
                content: {
                    "application/json": {
                        roles?: components["schemas"]["service.RoleSelection"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.DistributeRolesSuccessResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a game
         * @description Allows a player to join a game by name.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Game ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Player name */
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.PlayerResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get players in a game
         * @description Retrieves all players in a game.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Game ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.PlayerResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a player from a game
         * @description Removes a player from the game.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Game ID */
                    id: string;
                    /** @description Player ID */
                    player_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/players/{player_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a player's role
         * @description Retrieves the role assigned to a specific player.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Game ID */
                    id: string;
                    /** @description Player ID */
                    player_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.PlayerRoleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all role assignments in a game
         * @description Returns all player-role assignments for a game. Only the moderator can view this.
         */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Moderator identifier */
                    "X-Moderator-ID": string;
                };
                path: {
                    /** @description Game ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.GameRoleResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List role templates
         * @description Retrieves all role templates. Optionally filter by player_count.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by player count */
                    player_count?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleTemplateResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a role template by ID
         * @description Retrieves a single role template with its role assignments.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Template ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleTemplateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all roles
         * @description Retrieves all available roles in the game.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleResponse"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a role by slug
         * @description Retrieves a single role by its slug identifier.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.RoleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponseBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Admin user data */
        "handler.AdminResponse": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example admin@example.com */
            email?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example true */
            is_active?: boolean;
            /** @example 2024-01-01T00:00:00Z */
            last_login?: string;
            /** @example 2024-01-01T00:00:00Z */
            updated_at?: string;
            /** @example admin */
            username?: string;
        };
        /** @description Password change success response */
        "handler.ChangePasswordSuccessResponse": {
            /** @example password changed successfully */
            message?: string;
        };
        /** @description Role distribution success response */
        "handler.DistributeRolesSuccessResponse": {
            /** @example roles distributed successfully */
            message?: string;
        };
        /** @description Error response body */
        "handler.ErrorResponseBody": {
            /** @example something went wrong */
            error?: string;
        };
        /** @description Game data */
        "handler.GameResponse": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example mod-123 */
            moderator_id?: string;
            /**
             * @example waiting
             * @enum {string}
             */
            status?: "waiting" | "active" | "finished";
        };
        /** @description Moderator view of a player-role assignment */
        "handler.GameRoleResponse": {
            /** @example 2024-01-01T00:00:00Z */
            assigned_at?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            player_id?: string;
            /** @example Alice */
            player_name?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440001 */
            role_id?: string;
            /** @example Mafia */
            role_name?: string;
            /** @example mafia */
            role_slug?: string;
            /**
             * @example mafia
             * @enum {string}
             */
            team?: "mafia" | "village" | "independent";
            /** @example https://example.com/video.mp4 */
            video?: string;
        };
        /** @description Login response with token and admin info */
        "handler.LoginResponse": {
            admin?: components["schemas"]["handler.AdminResponse"];
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            token?: string;
        };
        /** @description Player data */
        "handler.PlayerResponse": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440001 */
            game_id?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example Alice */
            name?: string;
        };
        /** @description Player role assignment data */
        "handler.PlayerRoleResponse": {
            /**
             * @example [
             *       "eliminate"
             *     ]
             */
            abilities?: string[];
            /** @example 2024-01-01T00:00:00Z */
            assigned_at?: string;
            /** @example The mafia member eliminates villagers at night. */
            description?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example Mafia */
            name?: string;
            /** @example mafia */
            slug?: string;
            /**
             * @example mafia
             * @enum {string}
             */
            team?: "mafia" | "village" | "independent";
            /** @example https://example.com/video.mp4 */
            video?: string;
        };
        /** @description Role data */
        "handler.RoleResponse": {
            /**
             * @example [
             *       "eliminate"
             *     ]
             */
            abilities?: string[];
            /** @example The mafia member eliminates villagers at night. */
            description?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example Mafia */
            name?: string;
            /** @example mafia */
            slug?: string;
            /**
             * @example mafia
             * @enum {string}
             */
            team?: "mafia" | "village" | "independent";
            /** @example https://example.com/video.mp4 */
            video?: string;
        };
        /** @description Role template data */
        "handler.RoleTemplateResponse": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example Standard 8-player game setup */
            description?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example 8-player standard */
            name?: string;
            /** @example 8 */
            player_count?: number;
            roles?: components["schemas"]["handler.TemplateRoleEntryResponse"][];
            /** @example 2024-01-01T00:00:00Z */
            updated_at?: string;
        };
        /** @description Role entry in a template */
        "handler.TemplateRoleEntryResponse": {
            /** @example 2 */
            count?: number;
            role?: components["schemas"]["handler.RoleResponse"];
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            role_id?: string;
        };
        "service.RoleSelection": {
            count?: number;
            role_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
