// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mafia-night/backend/ent/admin"
	"github.com/mafia-night/backend/ent/predicate"
)

// AdminUpdate is the builder for updating Admin entities.
type AdminUpdate struct {
	config
	hooks    []Hook
	mutation *AdminMutation
}

// Where appends a list predicates to the AdminUpdate builder.
func (_u *AdminUpdate) Where(ps ...predicate.Admin) *AdminUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *AdminUpdate) SetUsername(v string) *AdminUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AdminUpdate) SetNillableUsername(v *string) *AdminUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AdminUpdate) SetEmail(v string) *AdminUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AdminUpdate) SetNillableEmail(v *string) *AdminUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AdminUpdate) SetPasswordHash(v string) *AdminUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AdminUpdate) SetNillablePasswordHash(v *string) *AdminUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminUpdate) SetIsActive(v bool) *AdminUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminUpdate) SetNillableIsActive(v *bool) *AdminUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminUpdate) SetUpdatedAt(v time.Time) *AdminUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *AdminUpdate) SetLastLogin(v time.Time) *AdminUpdate {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *AdminUpdate) SetNillableLastLogin(v *time.Time) *AdminUpdate {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *AdminUpdate) ClearLastLogin() *AdminUpdate {
	_u.mutation.ClearLastLogin()
	return _u
}

// Mutation returns the AdminMutation object of the builder.
func (_u *AdminUpdate) Mutation() *AdminMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := admin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := admin.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Admin.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := admin.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Admin.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := admin.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Admin.password_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admin.Table, admin.Columns, sqlgraph.NewFieldSpec(admin.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(admin.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(admin.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(admin.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(admin.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(admin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(admin.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(admin.FieldLastLogin, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminUpdateOne is the builder for updating a single Admin entity.
type AdminUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminMutation
}

// SetUsername sets the "username" field.
func (_u *AdminUpdateOne) SetUsername(v string) *AdminUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AdminUpdateOne) SetNillableUsername(v *string) *AdminUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AdminUpdateOne) SetEmail(v string) *AdminUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AdminUpdateOne) SetNillableEmail(v *string) *AdminUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AdminUpdateOne) SetPasswordHash(v string) *AdminUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AdminUpdateOne) SetNillablePasswordHash(v *string) *AdminUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminUpdateOne) SetIsActive(v bool) *AdminUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminUpdateOne) SetNillableIsActive(v *bool) *AdminUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminUpdateOne) SetUpdatedAt(v time.Time) *AdminUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *AdminUpdateOne) SetLastLogin(v time.Time) *AdminUpdateOne {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *AdminUpdateOne) SetNillableLastLogin(v *time.Time) *AdminUpdateOne {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *AdminUpdateOne) ClearLastLogin() *AdminUpdateOne {
	_u.mutation.ClearLastLogin()
	return _u
}

// Mutation returns the AdminMutation object of the builder.
func (_u *AdminUpdateOne) Mutation() *AdminMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminUpdate builder.
func (_u *AdminUpdateOne) Where(ps ...predicate.Admin) *AdminUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminUpdateOne) Select(field string, fields ...string) *AdminUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Admin entity.
func (_u *AdminUpdateOne) Save(ctx context.Context) (*Admin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUpdateOne) SaveX(ctx context.Context) *Admin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := admin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := admin.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Admin.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := admin.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Admin.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := admin.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Admin.password_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUpdateOne) sqlSave(ctx context.Context) (_node *Admin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admin.Table, admin.Columns, sqlgraph.NewFieldSpec(admin.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Admin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, admin.FieldID)
		for _, f := range fields {
			if !admin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != admin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(admin.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(admin.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(admin.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(admin.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(admin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(admin.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(admin.FieldLastLogin, field.TypeTime)
	}
	_node = &Admin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
