// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/ballot"
	"github.com/mafia-night/backend/ent/votesession"
)

// Ballot is the model entity for the Ballot schema.
type Ballot struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// VoterID holds the value of the "voter_id" field.
	VoterID uuid.UUID `json:"voter_id,omitempty"`
	// Choice holds the value of the "choice" field.
	Choice ballot.Choice `json:"choice,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BallotQuery when eager-loading is set.
	Edges        BallotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BallotEdges holds the relations/edges for other nodes in the graph.
type BallotEdges struct {
	// Session holds the value of the session edge.
	Session *VoteSession `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BallotEdges) SessionOrErr() (*VoteSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: votesession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ballot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ballot.FieldChoice:
			values[i] = new(sql.NullString)
		case ballot.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case ballot.FieldID, ballot.FieldSessionID, ballot.FieldVoterID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ballot fields.
func (_m *Ballot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ballot.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ballot.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case ballot.FieldVoterID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field voter_id", values[i])
			} else if value != nil {
				_m.VoterID = *value
			}
		case ballot.FieldChoice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field choice", values[i])
			} else if value.Valid {
				_m.Choice = ballot.Choice(value.String)
			}
		case ballot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ballot.
// This includes values selected through modifiers, order, etc.
func (_m *Ballot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the Ballot entity.
func (_m *Ballot) QuerySession() *VoteSessionQuery {
	return NewBallotClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this Ballot.
// Note that you need to call Ballot.Unwrap() before calling this method if this Ballot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ballot) Update() *BallotUpdateOne {
	return NewBallotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ballot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ballot) Unwrap() *Ballot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ballot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ballot) String() string {
	var builder strings.Builder
	builder.WriteString("Ballot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("voter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VoterID))
	builder.WriteString(", ")
	builder.WriteString("choice=")
	builder.WriteString(fmt.Sprintf("%v", _m.Choice))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Ballots is a parsable slice of Ballot.
type Ballots []*Ballot
