// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/ballot"
	"github.com/mafia-night/backend/ent/predicate"
	"github.com/mafia-night/backend/ent/votesession"
)

// BallotUpdate is the builder for updating Ballot entities.
type BallotUpdate struct {
	config
	hooks    []Hook
	mutation *BallotMutation
}

// Where appends a list predicates to the BallotUpdate builder.
func (_u *BallotUpdate) Where(ps ...predicate.Ballot) *BallotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *BallotUpdate) SetSessionID(v uuid.UUID) *BallotUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *BallotUpdate) SetNillableSessionID(v *uuid.UUID) *BallotUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetVoterID sets the "voter_id" field.
func (_u *BallotUpdate) SetVoterID(v uuid.UUID) *BallotUpdate {
	_u.mutation.SetVoterID(v)
	return _u
}

// SetNillableVoterID sets the "voter_id" field if the given value is not nil.
func (_u *BallotUpdate) SetNillableVoterID(v *uuid.UUID) *BallotUpdate {
	if v != nil {
		_u.SetVoterID(*v)
	}
	return _u
}

// SetChoice sets the "choice" field.
func (_u *BallotUpdate) SetChoice(v ballot.Choice) *BallotUpdate {
	_u.mutation.SetChoice(v)
	return _u
}

// SetNillableChoice sets the "choice" field if the given value is not nil.
func (_u *BallotUpdate) SetNillableChoice(v *ballot.Choice) *BallotUpdate {
	if v != nil {
		_u.SetChoice(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the VoteSession entity.
func (_u *BallotUpdate) SetSession(v *VoteSession) *BallotUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the BallotMutation object of the builder.
func (_u *BallotUpdate) Mutation() *BallotMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the VoteSession entity.
func (_u *BallotUpdate) ClearSession() *BallotUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BallotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BallotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BallotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BallotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BallotUpdate) check() error {
	if v, ok := _u.mutation.Choice(); ok {
		if err := ballot.ChoiceValidator(v); err != nil {
			return &ValidationError{Name: "choice", err: fmt.Errorf(`ent: validator failed for field "Ballot.choice": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ballot.session"`)
	}
	return nil
}

func (_u *BallotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ballot.Table, ballot.Columns, sqlgraph.NewFieldSpec(ballot.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VoterID(); ok {
		_spec.SetField(ballot.FieldVoterID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Choice(); ok {
		_spec.SetField(ballot.FieldChoice, field.TypeEnum, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ballot.SessionTable,
			Columns: []string{ballot.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ballot.SessionTable,
			Columns: []string{ballot.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ballot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BallotUpdateOne is the builder for updating a single Ballot entity.
type BallotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BallotMutation
}

// SetSessionID sets the "session_id" field.
func (_u *BallotUpdateOne) SetSessionID(v uuid.UUID) *BallotUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *BallotUpdateOne) SetNillableSessionID(v *uuid.UUID) *BallotUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetVoterID sets the "voter_id" field.
func (_u *BallotUpdateOne) SetVoterID(v uuid.UUID) *BallotUpdateOne {
	_u.mutation.SetVoterID(v)
	return _u
}

// SetNillableVoterID sets the "voter_id" field if the given value is not nil.
func (_u *BallotUpdateOne) SetNillableVoterID(v *uuid.UUID) *BallotUpdateOne {
	if v != nil {
		_u.SetVoterID(*v)
	}
	return _u
}

// SetChoice sets the "choice" field.
func (_u *BallotUpdateOne) SetChoice(v ballot.Choice) *BallotUpdateOne {
	_u.mutation.SetChoice(v)
	return _u
}

// SetNillableChoice sets the "choice" field if the given value is not nil.
func (_u *BallotUpdateOne) SetNillableChoice(v *ballot.Choice) *BallotUpdateOne {
	if v != nil {
		_u.SetChoice(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the VoteSession entity.
func (_u *BallotUpdateOne) SetSession(v *VoteSession) *BallotUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the BallotMutation object of the builder.
func (_u *BallotUpdateOne) Mutation() *BallotMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the VoteSession entity.
func (_u *BallotUpdateOne) ClearSession() *BallotUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the BallotUpdate builder.
func (_u *BallotUpdateOne) Where(ps ...predicate.Ballot) *BallotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BallotUpdateOne) Select(field string, fields ...string) *BallotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ballot entity.
func (_u *BallotUpdateOne) Save(ctx context.Context) (*Ballot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BallotUpdateOne) SaveX(ctx context.Context) *Ballot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BallotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BallotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BallotUpdateOne) check() error {
	if v, ok := _u.mutation.Choice(); ok {
		if err := ballot.ChoiceValidator(v); err != nil {
			return &ValidationError{Name: "choice", err: fmt.Errorf(`ent: validator failed for field "Ballot.choice": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ballot.session"`)
	}
	return nil
}

func (_u *BallotUpdateOne) sqlSave(ctx context.Context) (_node *Ballot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ballot.Table, ballot.Columns, sqlgraph.NewFieldSpec(ballot.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ballot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ballot.FieldID)
		for _, f := range fields {
			if !ballot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ballot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VoterID(); ok {
		_spec.SetField(ballot.FieldVoterID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Choice(); ok {
		_spec.SetField(ballot.FieldChoice, field.TypeEnum, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ballot.SessionTable,
			Columns: []string{ballot.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ballot.SessionTable,
			Columns: []string{ballot.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ballot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ballot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
