// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/elimination"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gameround"
	"github.com/mafia-night/backend/ent/player"
)

// EliminationCreate is the builder for creating a Elimination entity.
type EliminationCreate struct {
	config
	mutation *EliminationMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *EliminationCreate) SetGameID(v string) *EliminationCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetRoundID sets the "round_id" field.
func (_c *EliminationCreate) SetRoundID(v uuid.UUID) *EliminationCreate {
	_c.mutation.SetRoundID(v)
	return _c
}

// SetNillableRoundID sets the "round_id" field if the given value is not nil.
func (_c *EliminationCreate) SetNillableRoundID(v *uuid.UUID) *EliminationCreate {
	if v != nil {
		_c.SetRoundID(*v)
	}
	return _c
}

// SetPlayerID sets the "player_id" field.
func (_c *EliminationCreate) SetPlayerID(v uuid.UUID) *EliminationCreate {
	_c.mutation.SetPlayerID(v)
	return _c
}

// SetCause sets the "cause" field.
func (_c *EliminationCreate) SetCause(v elimination.Cause) *EliminationCreate {
	_c.mutation.SetCause(v)
	return _c
}

// SetEliminatedAt sets the "eliminated_at" field.
func (_c *EliminationCreate) SetEliminatedAt(v time.Time) *EliminationCreate {
	_c.mutation.SetEliminatedAt(v)
	return _c
}

// SetNillableEliminatedAt sets the "eliminated_at" field if the given value is not nil.
func (_c *EliminationCreate) SetNillableEliminatedAt(v *time.Time) *EliminationCreate {
	if v != nil {
		_c.SetEliminatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EliminationCreate) SetID(v uuid.UUID) *EliminationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EliminationCreate) SetNillableID(v *uuid.UUID) *EliminationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGame sets the "game" edge to the Game entity.
func (_c *EliminationCreate) SetGame(v *Game) *EliminationCreate {
	return _c.SetGameID(v.ID)
}

// SetRound sets the "round" edge to the GameRound entity.
func (_c *EliminationCreate) SetRound(v *GameRound) *EliminationCreate {
	return _c.SetRoundID(v.ID)
}

// SetPlayer sets the "player" edge to the Player entity.
func (_c *EliminationCreate) SetPlayer(v *Player) *EliminationCreate {
	return _c.SetPlayerID(v.ID)
}

// Mutation returns the EliminationMutation object of the builder.
func (_c *EliminationCreate) Mutation() *EliminationMutation {
	return _c.mutation
}

// Save creates the Elimination in the database.
func (_c *EliminationCreate) Save(ctx context.Context) (*Elimination, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EliminationCreate) SaveX(ctx context.Context) *Elimination {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EliminationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EliminationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EliminationCreate) defaults() {
	if _, ok := _c.mutation.EliminatedAt(); !ok {
		v := elimination.DefaultEliminatedAt()
		_c.mutation.SetEliminatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := elimination.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EliminationCreate) check() error {
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`ent: missing required field "Elimination.game_id"`)}
	}
	if v, ok := _c.mutation.GameID(); ok {
		if err := elimination.GameIDValidator(v); err != nil {
			return &ValidationError{Name: "game_id", err: fmt.Errorf(`ent: validator failed for field "Elimination.game_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "player_id", err: errors.New(`ent: missing required field "Elimination.player_id"`)}
	}
	if _, ok := _c.mutation.Cause(); !ok {
		return &ValidationError{Name: "cause", err: errors.New(`ent: missing required field "Elimination.cause"`)}
	}
	if v, ok := _c.mutation.Cause(); ok {
		if err := elimination.CauseValidator(v); err != nil {
			return &ValidationError{Name: "cause", err: fmt.Errorf(`ent: validator failed for field "Elimination.cause": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EliminatedAt(); !ok {
		return &ValidationError{Name: "eliminated_at", err: errors.New(`ent: missing required field "Elimination.eliminated_at"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "Elimination.game"`)}
	}
	if len(_c.mutation.PlayerIDs()) == 0 {
		return &ValidationError{Name: "player", err: errors.New(`ent: missing required edge "Elimination.player"`)}
	}
	return nil
}

func (_c *EliminationCreate) sqlSave(ctx context.Context) (*Elimination, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EliminationCreate) createSpec() (*Elimination, *sqlgraph.CreateSpec) {
	var (
		_node = &Elimination{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(elimination.Table, sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Cause(); ok {
		_spec.SetField(elimination.FieldCause, field.TypeEnum, value)
		_node.Cause = value
	}
	if value, ok := _c.mutation.EliminatedAt(); ok {
		_spec.SetField(elimination.FieldEliminatedAt, field.TypeTime, value)
		_node.EliminatedAt = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.GameTable,
			Columns: []string{elimination.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GameID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.RoundTable,
			Columns: []string{elimination.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoundID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   elimination.PlayerTable,
			Columns: []string{elimination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlayerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EliminationCreateBulk is the builder for creating many Elimination entities in bulk.
type EliminationCreateBulk struct {
	config
	err      error
	builders []*EliminationCreate
}

// Save creates the Elimination entities in the database.
func (_c *EliminationCreateBulk) Save(ctx context.Context) ([]*Elimination, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Elimination, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EliminationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EliminationCreateBulk) SaveX(ctx context.Context) []*Elimination {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EliminationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EliminationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
