// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/elimination"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gameround"
	"github.com/mafia-night/backend/ent/player"
)

// Elimination is the model entity for the Elimination schema.
type Elimination struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID string `json:"game_id,omitempty"`
	// RoundID holds the value of the "round_id" field.
	RoundID *uuid.UUID `json:"round_id,omitempty"`
	// PlayerID holds the value of the "player_id" field.
	PlayerID uuid.UUID `json:"player_id,omitempty"`
	// Cause holds the value of the "cause" field.
	Cause elimination.Cause `json:"cause,omitempty"`
	// EliminatedAt holds the value of the "eliminated_at" field.
	EliminatedAt time.Time `json:"eliminated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EliminationQuery when eager-loading is set.
	Edges        EliminationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EliminationEdges holds the relations/edges for other nodes in the graph.
type EliminationEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// Round holds the value of the round edge.
	Round *GameRound `json:"round,omitempty"`
	// Player holds the value of the player edge.
	Player *Player `json:"player,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EliminationEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// RoundOrErr returns the Round value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EliminationEdges) RoundOrErr() (*GameRound, error) {
	if e.Round != nil {
		return e.Round, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: gameround.Label}
	}
	return nil, &NotLoadedError{edge: "round"}
}

// PlayerOrErr returns the Player value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EliminationEdges) PlayerOrErr() (*Player, error) {
	if e.Player != nil {
		return e.Player, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "player"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Elimination) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case elimination.FieldRoundID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case elimination.FieldGameID, elimination.FieldCause:
			values[i] = new(sql.NullString)
		case elimination.FieldEliminatedAt:
			values[i] = new(sql.NullTime)
		case elimination.FieldID, elimination.FieldPlayerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Elimination fields.
func (_m *Elimination) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case elimination.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case elimination.FieldGameID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = value.String
			}
		case elimination.FieldRoundID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field round_id", values[i])
			} else if value.Valid {
				_m.RoundID = new(uuid.UUID)
				*_m.RoundID = *value.S.(*uuid.UUID)
			}
		case elimination.FieldPlayerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field player_id", values[i])
			} else if value != nil {
				_m.PlayerID = *value
			}
		case elimination.FieldCause:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cause", values[i])
			} else if value.Valid {
				_m.Cause = elimination.Cause(value.String)
			}
		case elimination.FieldEliminatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field eliminated_at", values[i])
			} else if value.Valid {
				_m.EliminatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Elimination.
// This includes values selected through modifiers, order, etc.
func (_m *Elimination) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the Elimination entity.
func (_m *Elimination) QueryGame() *GameQuery {
	return NewEliminationClient(_m.config).QueryGame(_m)
}

// QueryRound queries the "round" edge of the Elimination entity.
func (_m *Elimination) QueryRound() *GameRoundQuery {
	return NewEliminationClient(_m.config).QueryRound(_m)
}

// QueryPlayer queries the "player" edge of the Elimination entity.
func (_m *Elimination) QueryPlayer() *PlayerQuery {
	return NewEliminationClient(_m.config).QueryPlayer(_m)
}

// Update returns a builder for updating this Elimination.
// Note that you need to call Elimination.Unwrap() before calling this method if this Elimination
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Elimination) Update() *EliminationUpdateOne {
	return NewEliminationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Elimination entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Elimination) Unwrap() *Elimination {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Elimination is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Elimination) String() string {
	var builder strings.Builder
	builder.WriteString("Elimination(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("game_id=")
	builder.WriteString(_m.GameID)
	builder.WriteString(", ")
	if v := _m.RoundID; v != nil {
		builder.WriteString("round_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("player_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlayerID))
	builder.WriteString(", ")
	builder.WriteString("cause=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cause))
	builder.WriteString(", ")
	builder.WriteString("eliminated_at=")
	builder.WriteString(_m.EliminatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Eliminations is a parsable slice of Elimination.
type Eliminations []*Elimination
