// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/elimination"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gameround"
	"github.com/mafia-night/backend/ent/player"
	"github.com/mafia-night/backend/ent/predicate"
)

// EliminationUpdate is the builder for updating Elimination entities.
type EliminationUpdate struct {
	config
	hooks    []Hook
	mutation *EliminationMutation
}

// Where appends a list predicates to the EliminationUpdate builder.
func (_u *EliminationUpdate) Where(ps ...predicate.Elimination) *EliminationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *EliminationUpdate) SetGameID(v string) *EliminationUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *EliminationUpdate) SetNillableGameID(v *string) *EliminationUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRoundID sets the "round_id" field.
func (_u *EliminationUpdate) SetRoundID(v uuid.UUID) *EliminationUpdate {
	_u.mutation.SetRoundID(v)
	return _u
}

// SetNillableRoundID sets the "round_id" field if the given value is not nil.
func (_u *EliminationUpdate) SetNillableRoundID(v *uuid.UUID) *EliminationUpdate {
	if v != nil {
		_u.SetRoundID(*v)
	}
	return _u
}

// ClearRoundID clears the value of the "round_id" field.
func (_u *EliminationUpdate) ClearRoundID() *EliminationUpdate {
	_u.mutation.ClearRoundID()
	return _u
}

// SetPlayerID sets the "player_id" field.
func (_u *EliminationUpdate) SetPlayerID(v uuid.UUID) *EliminationUpdate {
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *EliminationUpdate) SetNillablePlayerID(v *uuid.UUID) *EliminationUpdate {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// SetCause sets the "cause" field.
func (_u *EliminationUpdate) SetCause(v elimination.Cause) *EliminationUpdate {
	_u.mutation.SetCause(v)
	return _u
}

// SetNillableCause sets the "cause" field if the given value is not nil.
func (_u *EliminationUpdate) SetNillableCause(v *elimination.Cause) *EliminationUpdate {
	if v != nil {
		_u.SetCause(*v)
	}
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *EliminationUpdate) SetGame(v *Game) *EliminationUpdate {
	return _u.SetGameID(v.ID)
}

// SetRound sets the "round" edge to the GameRound entity.
func (_u *EliminationUpdate) SetRound(v *GameRound) *EliminationUpdate {
	return _u.SetRoundID(v.ID)
}

// SetPlayer sets the "player" edge to the Player entity.
func (_u *EliminationUpdate) SetPlayer(v *Player) *EliminationUpdate {
	return _u.SetPlayerID(v.ID)
}

// Mutation returns the EliminationMutation object of the builder.
func (_u *EliminationUpdate) Mutation() *EliminationMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *EliminationUpdate) ClearGame() *EliminationUpdate {
	_u.mutation.ClearGame()
	return _u
}

// ClearRound clears the "round" edge to the GameRound entity.
func (_u *EliminationUpdate) ClearRound() *EliminationUpdate {
	_u.mutation.ClearRound()
	return _u
}

// ClearPlayer clears the "player" edge to the Player entity.
func (_u *EliminationUpdate) ClearPlayer() *EliminationUpdate {
	_u.mutation.ClearPlayer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EliminationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EliminationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EliminationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EliminationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EliminationUpdate) check() error {
	if v, ok := _u.mutation.GameID(); ok {
		if err := elimination.GameIDValidator(v); err != nil {
			return &ValidationError{Name: "game_id", err: fmt.Errorf(`ent: validator failed for field "Elimination.game_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cause(); ok {
		if err := elimination.CauseValidator(v); err != nil {
			return &ValidationError{Name: "cause", err: fmt.Errorf(`ent: validator failed for field "Elimination.cause": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Elimination.game"`)
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Elimination.player"`)
	}
	return nil
}

func (_u *EliminationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(elimination.Table, elimination.Columns, sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cause(); ok {
		_spec.SetField(elimination.FieldCause, field.TypeEnum, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.GameTable,
			Columns: []string{elimination.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.GameTable,
			Columns: []string{elimination.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.RoundTable,
			Columns: []string{elimination.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.RoundTable,
			Columns: []string{elimination.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   elimination.PlayerTable,
			Columns: []string{elimination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   elimination.PlayerTable,
			Columns: []string{elimination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{elimination.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EliminationUpdateOne is the builder for updating a single Elimination entity.
type EliminationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EliminationMutation
}

// SetGameID sets the "game_id" field.
func (_u *EliminationUpdateOne) SetGameID(v string) *EliminationUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *EliminationUpdateOne) SetNillableGameID(v *string) *EliminationUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRoundID sets the "round_id" field.
func (_u *EliminationUpdateOne) SetRoundID(v uuid.UUID) *EliminationUpdateOne {
	_u.mutation.SetRoundID(v)
	return _u
}

// SetNillableRoundID sets the "round_id" field if the given value is not nil.
func (_u *EliminationUpdateOne) SetNillableRoundID(v *uuid.UUID) *EliminationUpdateOne {
	if v != nil {
		_u.SetRoundID(*v)
	}
	return _u
}

// ClearRoundID clears the value of the "round_id" field.
func (_u *EliminationUpdateOne) ClearRoundID() *EliminationUpdateOne {
	_u.mutation.ClearRoundID()
	return _u
}

// SetPlayerID sets the "player_id" field.
func (_u *EliminationUpdateOne) SetPlayerID(v uuid.UUID) *EliminationUpdateOne {
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *EliminationUpdateOne) SetNillablePlayerID(v *uuid.UUID) *EliminationUpdateOne {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// SetCause sets the "cause" field.
func (_u *EliminationUpdateOne) SetCause(v elimination.Cause) *EliminationUpdateOne {
	_u.mutation.SetCause(v)
	return _u
}

// SetNillableCause sets the "cause" field if the given value is not nil.
func (_u *EliminationUpdateOne) SetNillableCause(v *elimination.Cause) *EliminationUpdateOne {
	if v != nil {
		_u.SetCause(*v)
	}
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *EliminationUpdateOne) SetGame(v *Game) *EliminationUpdateOne {
	return _u.SetGameID(v.ID)
}

// SetRound sets the "round" edge to the GameRound entity.
func (_u *EliminationUpdateOne) SetRound(v *GameRound) *EliminationUpdateOne {
	return _u.SetRoundID(v.ID)
}

// SetPlayer sets the "player" edge to the Player entity.
func (_u *EliminationUpdateOne) SetPlayer(v *Player) *EliminationUpdateOne {
	return _u.SetPlayerID(v.ID)
}

// Mutation returns the EliminationMutation object of the builder.
func (_u *EliminationUpdateOne) Mutation() *EliminationMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *EliminationUpdateOne) ClearGame() *EliminationUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// ClearRound clears the "round" edge to the GameRound entity.
func (_u *EliminationUpdateOne) ClearRound() *EliminationUpdateOne {
	_u.mutation.ClearRound()
	return _u
}

// ClearPlayer clears the "player" edge to the Player entity.
func (_u *EliminationUpdateOne) ClearPlayer() *EliminationUpdateOne {
	_u.mutation.ClearPlayer()
	return _u
}

// Where appends a list predicates to the EliminationUpdate builder.
func (_u *EliminationUpdateOne) Where(ps ...predicate.Elimination) *EliminationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EliminationUpdateOne) Select(field string, fields ...string) *EliminationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Elimination entity.
func (_u *EliminationUpdateOne) Save(ctx context.Context) (*Elimination, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EliminationUpdateOne) SaveX(ctx context.Context) *Elimination {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EliminationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EliminationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EliminationUpdateOne) check() error {
	if v, ok := _u.mutation.GameID(); ok {
		if err := elimination.GameIDValidator(v); err != nil {
			return &ValidationError{Name: "game_id", err: fmt.Errorf(`ent: validator failed for field "Elimination.game_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cause(); ok {
		if err := elimination.CauseValidator(v); err != nil {
			return &ValidationError{Name: "cause", err: fmt.Errorf(`ent: validator failed for field "Elimination.cause": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Elimination.game"`)
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Elimination.player"`)
	}
	return nil
}

func (_u *EliminationUpdateOne) sqlSave(ctx context.Context) (_node *Elimination, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(elimination.Table, elimination.Columns, sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Elimination.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, elimination.FieldID)
		for _, f := range fields {
			if !elimination.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != elimination.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cause(); ok {
		_spec.SetField(elimination.FieldCause, field.TypeEnum, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.GameTable,
			Columns: []string{elimination.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.GameTable,
			Columns: []string{elimination.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.RoundTable,
			Columns: []string{elimination.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   elimination.RoundTable,
			Columns: []string{elimination.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   elimination.PlayerTable,
			Columns: []string{elimination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   elimination.PlayerTable,
			Columns: []string{elimination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Elimination{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{elimination.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
