// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gameround"
)

// GameRound is the model entity for the GameRound schema.
type GameRound struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID string `json:"game_id,omitempty"`
	// RoundNumber holds the value of the "round_number" field.
	RoundNumber int `json:"round_number,omitempty"`
	// Phase holds the value of the "phase" field.
	Phase gameround.Phase `json:"phase,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameRoundQuery when eager-loading is set.
	Edges        GameRoundEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GameRoundEdges holds the relations/edges for other nodes in the graph.
type GameRoundEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// Eliminations holds the value of the eliminations edge.
	Eliminations []*Elimination `json:"eliminations,omitempty"`
	// Votes holds the value of the votes edge.
	Votes []*Vote `json:"votes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameRoundEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// EliminationsOrErr returns the Eliminations value or an error if the edge
// was not loaded in eager-loading.
func (e GameRoundEdges) EliminationsOrErr() ([]*Elimination, error) {
	if e.loadedTypes[1] {
		return e.Eliminations, nil
	}
	return nil, &NotLoadedError{edge: "eliminations"}
}

// VotesOrErr returns the Votes value or an error if the edge
// was not loaded in eager-loading.
func (e GameRoundEdges) VotesOrErr() ([]*Vote, error) {
	if e.loadedTypes[2] {
		return e.Votes, nil
	}
	return nil, &NotLoadedError{edge: "votes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GameRound) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gameround.FieldRoundNumber:
			values[i] = new(sql.NullInt64)
		case gameround.FieldGameID, gameround.FieldPhase:
			values[i] = new(sql.NullString)
		case gameround.FieldStartedAt, gameround.FieldEndedAt:
			values[i] = new(sql.NullTime)
		case gameround.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GameRound fields.
func (_m *GameRound) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gameround.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case gameround.FieldGameID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = value.String
			}
		case gameround.FieldRoundNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field round_number", values[i])
			} else if value.Valid {
				_m.RoundNumber = int(value.Int64)
			}
		case gameround.FieldPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				_m.Phase = gameround.Phase(value.String)
			}
		case gameround.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case gameround.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GameRound.
// This includes values selected through modifiers, order, etc.
func (_m *GameRound) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the GameRound entity.
func (_m *GameRound) QueryGame() *GameQuery {
	return NewGameRoundClient(_m.config).QueryGame(_m)
}

// QueryEliminations queries the "eliminations" edge of the GameRound entity.
func (_m *GameRound) QueryEliminations() *EliminationQuery {
	return NewGameRoundClient(_m.config).QueryEliminations(_m)
}

// QueryVotes queries the "votes" edge of the GameRound entity.
func (_m *GameRound) QueryVotes() *VoteQuery {
	return NewGameRoundClient(_m.config).QueryVotes(_m)
}

// Update returns a builder for updating this GameRound.
// Note that you need to call GameRound.Unwrap() before calling this method if this GameRound
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GameRound) Update() *GameRoundUpdateOne {
	return NewGameRoundClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GameRound entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GameRound) Unwrap() *GameRound {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GameRound is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GameRound) String() string {
	var builder strings.Builder
	builder.WriteString("GameRound(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("game_id=")
	builder.WriteString(_m.GameID)
	builder.WriteString(", ")
	builder.WriteString("round_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoundNumber))
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(fmt.Sprintf("%v", _m.Phase))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GameRounds is a parsable slice of GameRound.
type GameRounds []*GameRound
