// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gamerole"
	"github.com/mafia-night/backend/ent/player"
	"github.com/mafia-night/backend/ent/role"
)

// GameRoleCreate is the builder for creating a GameRole entity.
type GameRoleCreate struct {
	config
	mutation *GameRoleMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *GameRoleCreate) SetGameID(v string) *GameRoleCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetPlayerID sets the "player_id" field.
func (_c *GameRoleCreate) SetPlayerID(v uuid.UUID) *GameRoleCreate {
	_c.mutation.SetPlayerID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *GameRoleCreate) SetRoleID(v uuid.UUID) *GameRoleCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *GameRoleCreate) SetAssignedAt(v time.Time) *GameRoleCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *GameRoleCreate) SetNillableAssignedAt(v *time.Time) *GameRoleCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetGame sets the "game" edge to the Game entity.
func (_c *GameRoleCreate) SetGame(v *Game) *GameRoleCreate {
	return _c.SetGameID(v.ID)
}

// SetPlayer sets the "player" edge to the Player entity.
func (_c *GameRoleCreate) SetPlayer(v *Player) *GameRoleCreate {
	return _c.SetPlayerID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_c *GameRoleCreate) SetRole(v *Role) *GameRoleCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the GameRoleMutation object of the builder.
func (_c *GameRoleCreate) Mutation() *GameRoleMutation {
	return _c.mutation
}

// Save creates the GameRole in the database.
func (_c *GameRoleCreate) Save(ctx context.Context) (*GameRole, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GameRoleCreate) SaveX(ctx context.Context) *GameRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameRoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameRoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GameRoleCreate) defaults() {
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := gamerole.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GameRoleCreate) check() error {
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`ent: missing required field "GameRole.game_id"`)}
	}
	if v, ok := _c.mutation.GameID(); ok {
		if err := gamerole.GameIDValidator(v); err != nil {
			return &ValidationError{Name: "game_id", err: fmt.Errorf(`ent: validator failed for field "GameRole.game_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "player_id", err: errors.New(`ent: missing required field "GameRole.player_id"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "GameRole.role_id"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "GameRole.assigned_at"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "GameRole.game"`)}
	}
	if len(_c.mutation.PlayerIDs()) == 0 {
		return &ValidationError{Name: "player", err: errors.New(`ent: missing required edge "GameRole.player"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "GameRole.role"`)}
	}
	return nil
}

func (_c *GameRoleCreate) sqlSave(ctx context.Context) (*GameRole, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GameRoleCreate) createSpec() (*GameRole, *sqlgraph.CreateSpec) {
	var (
		_node = &GameRole{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gamerole.Table, sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(gamerole.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamerole.GameTable,
			Columns: []string{gamerole.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GameID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   gamerole.PlayerTable,
			Columns: []string{gamerole.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlayerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamerole.RoleTable,
			Columns: []string{gamerole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GameRoleCreateBulk is the builder for creating many GameRole entities in bulk.
type GameRoleCreateBulk struct {
	config
	err      error
	builders []*GameRoleCreate
}

// Save creates the GameRole entities in the database.
func (_c *GameRoleCreateBulk) Save(ctx context.Context) ([]*GameRole, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GameRole, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GameRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GameRoleCreateBulk) SaveX(ctx context.Context) []*GameRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameRoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
