// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gamerole"
	"github.com/mafia-night/backend/ent/player"
	"github.com/mafia-night/backend/ent/predicate"
	"github.com/mafia-night/backend/ent/role"
)

// GameRoleQuery is the builder for querying GameRole entities.
type GameRoleQuery struct {
	config
	ctx        *QueryContext
	order      []gamerole.OrderOption
	inters     []Interceptor
	predicates []predicate.GameRole
	withGame   *GameQuery
	withPlayer *PlayerQuery
	withRole   *RoleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GameRoleQuery builder.
func (_q *GameRoleQuery) Where(ps ...predicate.GameRole) *GameRoleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GameRoleQuery) Limit(limit int) *GameRoleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GameRoleQuery) Offset(offset int) *GameRoleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GameRoleQuery) Unique(unique bool) *GameRoleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GameRoleQuery) Order(o ...gamerole.OrderOption) *GameRoleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGame chains the current query on the "game" edge.
func (_q *GameRoleQuery) QueryGame() *GameQuery {
	query := (&GameClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gamerole.Table, gamerole.FieldID, selector),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gamerole.GameTable, gamerole.GameColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlayer chains the current query on the "player" edge.
func (_q *GameRoleQuery) QueryPlayer() *PlayerQuery {
	query := (&PlayerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gamerole.Table, gamerole.FieldID, selector),
			sqlgraph.To(player.Table, player.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, gamerole.PlayerTable, gamerole.PlayerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRole chains the current query on the "role" edge.
func (_q *GameRoleQuery) QueryRole() *RoleQuery {
	query := (&RoleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gamerole.Table, gamerole.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gamerole.RoleTable, gamerole.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GameRole entity from the query.
// Returns a *NotFoundError when no GameRole was found.
func (_q *GameRoleQuery) First(ctx context.Context) (*GameRole, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gamerole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GameRoleQuery) FirstX(ctx context.Context) *GameRole {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GameRole ID from the query.
// Returns a *NotFoundError when no GameRole ID was found.
func (_q *GameRoleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gamerole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GameRoleQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GameRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GameRole entity is found.
// Returns a *NotFoundError when no GameRole entities are found.
func (_q *GameRoleQuery) Only(ctx context.Context) (*GameRole, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gamerole.Label}
	default:
		return nil, &NotSingularError{gamerole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GameRoleQuery) OnlyX(ctx context.Context) *GameRole {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GameRole ID in the query.
// Returns a *NotSingularError when more than one GameRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GameRoleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gamerole.Label}
	default:
		err = &NotSingularError{gamerole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GameRoleQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GameRoles.
func (_q *GameRoleQuery) All(ctx context.Context) ([]*GameRole, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GameRole, *GameRoleQuery]()
	return withInterceptors[[]*GameRole](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GameRoleQuery) AllX(ctx context.Context) []*GameRole {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GameRole IDs.
func (_q *GameRoleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(gamerole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GameRoleQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GameRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GameRoleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GameRoleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GameRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GameRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GameRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GameRoleQuery) Clone() *GameRoleQuery {
	if _q == nil {
		return nil
	}
	return &GameRoleQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]gamerole.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.GameRole{}, _q.predicates...),
		withGame:   _q.withGame.Clone(),
		withPlayer: _q.withPlayer.Clone(),
		withRole:   _q.withRole.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGame tells the query-builder to eager-load the nodes that are connected to
// the "game" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GameRoleQuery) WithGame(opts ...func(*GameQuery)) *GameRoleQuery {
	query := (&GameClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGame = query
	return _q
}

// WithPlayer tells the query-builder to eager-load the nodes that are connected to
// the "player" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GameRoleQuery) WithPlayer(opts ...func(*PlayerQuery)) *GameRoleQuery {
	query := (&PlayerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlayer = query
	return _q
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GameRoleQuery) WithRole(opts ...func(*RoleQuery)) *GameRoleQuery {
	query := (&RoleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRole = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GameID string `json:"game_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GameRole.Query().
//		GroupBy(gamerole.FieldGameID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GameRoleQuery) GroupBy(field string, fields ...string) *GameRoleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GameRoleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = gamerole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GameID string `json:"game_id,omitempty"`
//	}
//
//	client.GameRole.Query().
//		Select(gamerole.FieldGameID).
//		Scan(ctx, &v)
func (_q *GameRoleQuery) Select(fields ...string) *GameRoleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GameRoleSelect{GameRoleQuery: _q}
	sbuild.label = gamerole.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GameRoleSelect configured with the given aggregations.
func (_q *GameRoleQuery) Aggregate(fns ...AggregateFunc) *GameRoleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GameRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !gamerole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GameRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GameRole, error) {
	var (
		nodes       = []*GameRole{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withGame != nil,
			_q.withPlayer != nil,
			_q.withRole != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GameRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GameRole{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGame; query != nil {
		if err := _q.loadGame(ctx, query, nodes, nil,
			func(n *GameRole, e *Game) { n.Edges.Game = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPlayer; query != nil {
		if err := _q.loadPlayer(ctx, query, nodes, nil,
			func(n *GameRole, e *Player) { n.Edges.Player = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRole; query != nil {
		if err := _q.loadRole(ctx, query, nodes, nil,
			func(n *GameRole, e *Role) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GameRoleQuery) loadGame(ctx context.Context, query *GameQuery, nodes []*GameRole, init func(*GameRole), assign func(*GameRole, *Game)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*GameRole)
	for i := range nodes {
		fk := nodes[i].GameID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(game.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GameRoleQuery) loadPlayer(ctx context.Context, query *PlayerQuery, nodes []*GameRole, init func(*GameRole), assign func(*GameRole, *Player)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GameRole)
	for i := range nodes {
		fk := nodes[i].PlayerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(player.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "player_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GameRoleQuery) loadRole(ctx context.Context, query *RoleQuery, nodes []*GameRole, init func(*GameRole), assign func(*GameRole, *Role)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GameRole)
	for i := range nodes {
		fk := nodes[i].RoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *GameRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GameRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(gamerole.Table, gamerole.Columns, sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamerole.FieldID)
		for i := range fields {
			if fields[i] != gamerole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGame != nil {
			_spec.Node.AddColumnOnce(gamerole.FieldGameID)
		}
		if _q.withPlayer != nil {
			_spec.Node.AddColumnOnce(gamerole.FieldPlayerID)
		}
		if _q.withRole != nil {
			_spec.Node.AddColumnOnce(gamerole.FieldRoleID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GameRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(gamerole.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = gamerole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GameRoleGroupBy is the group-by builder for GameRole entities.
type GameRoleGroupBy struct {
	selector
	build *GameRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GameRoleGroupBy) Aggregate(fns ...AggregateFunc) *GameRoleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GameRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	
	return scanWithInterceptors[*GameRoleQuery, *GameRoleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GameRoleGroupBy) sqlScan(ctx context.Context, root *GameRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GameRoleSelect is the builder for selecting fields of GameRole entities.
type GameRoleSelect struct {
	*GameRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GameRoleSelect) Aggregate(fns ...AggregateFunc) *GameRoleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GameRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GameRoleQuery, *GameRoleSelect](ctx, _s.GameRoleQuery, _s, _s.inters, v)
}

func (_s *GameRoleSelect) sqlScan(ctx context.Context, root *GameRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
