// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/elimination"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gamerole"
	"github.com/mafia-night/backend/ent/gameround"
	"github.com/mafia-night/backend/ent/player"
	"github.com/mafia-night/backend/ent/predicate"
	"github.com/mafia-night/backend/ent/vote"
	"github.com/mafia-night/backend/ent/votesession"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GameUpdate) SetStatus(v game.Status) *GameUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameUpdate) SetNillableStatus(v *game.Status) *GameUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *GameUpdate) SetPhase(v game.Phase) *GameUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *GameUpdate) SetNillablePhase(v *game.Phase) *GameUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetRoundNumber sets the "round_number" field.
func (_u *GameUpdate) SetRoundNumber(v int) *GameUpdate {
	_u.mutation.ResetRoundNumber()
	_u.mutation.SetRoundNumber(v)
	return _u
}

// SetNillableRoundNumber sets the "round_number" field if the given value is not nil.
func (_u *GameUpdate) SetNillableRoundNumber(v *int) *GameUpdate {
	if v != nil {
		_u.SetRoundNumber(*v)
	}
	return _u
}

// AddRoundNumber adds value to the "round_number" field.
func (_u *GameUpdate) AddRoundNumber(v int) *GameUpdate {
	_u.mutation.AddRoundNumber(v)
	return _u
}

// SetModeratorID sets the "moderator_id" field.
func (_u *GameUpdate) SetModeratorID(v string) *GameUpdate {
	_u.mutation.SetModeratorID(v)
	return _u
}

// SetNillableModeratorID sets the "moderator_id" field if the given value is not nil.
func (_u *GameUpdate) SetNillableModeratorID(v *string) *GameUpdate {
	if v != nil {
		_u.SetModeratorID(*v)
	}
	return _u
}

// AddPlayerIDs adds the "players" edge to the Player entity by IDs.
func (_u *GameUpdate) AddPlayerIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the Player entity.
func (_u *GameUpdate) AddPlayers(v ...*Player) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// AddGameRoleIDs adds the "game_roles" edge to the GameRole entity by IDs.
func (_u *GameUpdate) AddGameRoleIDs(ids ...int) *GameUpdate {
	_u.mutation.AddGameRoleIDs(ids...)
	return _u
}

// AddGameRoles adds the "game_roles" edges to the GameRole entity.
func (_u *GameUpdate) AddGameRoles(v ...*GameRole) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGameRoleIDs(ids...)
}

// AddRoundIDs adds the "rounds" edge to the GameRound entity by IDs.
func (_u *GameUpdate) AddRoundIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.AddRoundIDs(ids...)
	return _u
}

// AddRounds adds the "rounds" edges to the GameRound entity.
func (_u *GameUpdate) AddRounds(v ...*GameRound) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoundIDs(ids...)
}

// AddEliminationIDs adds the "eliminations" edge to the Elimination entity by IDs.
func (_u *GameUpdate) AddEliminationIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.AddEliminationIDs(ids...)
	return _u
}

// AddEliminations adds the "eliminations" edges to the Elimination entity.
func (_u *GameUpdate) AddEliminations(v ...*Elimination) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEliminationIDs(ids...)
}

// AddVoteSessionIDs adds the "vote_sessions" edge to the VoteSession entity by IDs.
func (_u *GameUpdate) AddVoteSessionIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.AddVoteSessionIDs(ids...)
	return _u
}

// AddVoteSessions adds the "vote_sessions" edges to the VoteSession entity.
func (_u *GameUpdate) AddVoteSessions(v ...*VoteSession) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteSessionIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the Vote entity by IDs.
func (_u *GameUpdate) AddVoteIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.AddVoteIDs(ids...)
	return _u
}

// AddVotes adds the "votes" edges to the Vote entity.
func (_u *GameUpdate) AddVotes(v ...*Vote) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the Player entity.
func (_u *GameUpdate) ClearPlayers() *GameUpdate {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to Player entities by IDs.
func (_u *GameUpdate) RemovePlayerIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to Player entities.
func (_u *GameUpdate) RemovePlayers(v ...*Player) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearGameRoles clears all "game_roles" edges to the GameRole entity.
func (_u *GameUpdate) ClearGameRoles() *GameUpdate {
	_u.mutation.ClearGameRoles()
	return _u
}

// RemoveGameRoleIDs removes the "game_roles" edge to GameRole entities by IDs.
func (_u *GameUpdate) RemoveGameRoleIDs(ids ...int) *GameUpdate {
	_u.mutation.RemoveGameRoleIDs(ids...)
	return _u
}

// RemoveGameRoles removes "game_roles" edges to GameRole entities.
func (_u *GameUpdate) RemoveGameRoles(v ...*GameRole) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGameRoleIDs(ids...)
}

// ClearRounds clears all "rounds" edges to the GameRound entity.
func (_u *GameUpdate) ClearRounds() *GameUpdate {
	_u.mutation.ClearRounds()
	return _u
}

// RemoveRoundIDs removes the "rounds" edge to GameRound entities by IDs.
func (_u *GameUpdate) RemoveRoundIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.RemoveRoundIDs(ids...)
	return _u
}

// RemoveRounds removes "rounds" edges to GameRound entities.
func (_u *GameUpdate) RemoveRounds(v ...*GameRound) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoundIDs(ids...)
}

// ClearEliminations clears all "eliminations" edges to the Elimination entity.
func (_u *GameUpdate) ClearEliminations() *GameUpdate {
	_u.mutation.ClearEliminations()
	return _u
}

// RemoveEliminationIDs removes the "eliminations" edge to Elimination entities by IDs.
func (_u *GameUpdate) RemoveEliminationIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.RemoveEliminationIDs(ids...)
	return _u
}

// RemoveEliminations removes "eliminations" edges to Elimination entities.
func (_u *GameUpdate) RemoveEliminations(v ...*Elimination) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEliminationIDs(ids...)
}

// ClearVoteSessions clears all "vote_sessions" edges to the VoteSession entity.
func (_u *GameUpdate) ClearVoteSessions() *GameUpdate {
	_u.mutation.ClearVoteSessions()
	return _u
}

// RemoveVoteSessionIDs removes the "vote_sessions" edge to VoteSession entities by IDs.
func (_u *GameUpdate) RemoveVoteSessionIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.RemoveVoteSessionIDs(ids...)
	return _u
}

// RemoveVoteSessions removes "vote_sessions" edges to VoteSession entities.
func (_u *GameUpdate) RemoveVoteSessions(v ...*VoteSession) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteSessionIDs(ids...)
}

// ClearVotes clears all "votes" edges to the Vote entity.
func (_u *GameUpdate) ClearVotes() *GameUpdate {
	_u.mutation.ClearVotes()
	return _u
}

// RemoveVoteIDs removes the "votes" edge to Vote entities by IDs.
func (_u *GameUpdate) RemoveVoteIDs(ids ...uuid.UUID) *GameUpdate {
	_u.mutation.RemoveVoteIDs(ids...)
	return _u
}

// RemoveVotes removes "votes" edges to Vote entities.
func (_u *GameUpdate) RemoveVotes(v ...*Vote) *GameUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := game.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Game.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := game.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Game.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoundNumber(); ok {
		if err := game.RoundNumberValidator(v); err != nil {
			return &ValidationError{Name: "round_number", err: fmt.Errorf(`ent: validator failed for field "Game.round_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModeratorID(); ok {
		if err := game.ModeratorIDValidator(v); err != nil {
			return &ValidationError{Name: "moderator_id", err: fmt.Errorf(`ent: validator failed for field "Game.moderator_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(game.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(game.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RoundNumber(); ok {
		_spec.SetField(game.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundNumber(); ok {
		_spec.AddField(game.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ModeratorID(); ok {
		_spec.SetField(game.FieldModeratorID, field.TypeString, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GameRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.GameRolesTable,
			Columns: []string{game.GameRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGameRolesIDs(); len(nodes) > 0 && !_u.mutation.GameRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.GameRolesTable,
			Columns: []string{game.GameRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.GameRolesTable,
			Columns: []string{game.GameRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.RoundsTable,
			Columns: []string{game.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoundsIDs(); len(nodes) > 0 && !_u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.RoundsTable,
			Columns: []string{game.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.RoundsTable,
			Columns: []string{game.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EliminationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.EliminationsTable,
			Columns: []string{game.EliminationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEliminationsIDs(); len(nodes) > 0 && !_u.mutation.EliminationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.EliminationsTable,
			Columns: []string{game.EliminationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EliminationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.EliminationsTable,
			Columns: []string{game.EliminationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VoteSessionsTable,
			Columns: []string{game.VoteSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteSessionsIDs(); len(nodes) > 0 && !_u.mutation.VoteSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VoteSessionsTable,
			Columns: []string{game.VoteSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VoteSessionsTable,
			Columns: []string{game.VoteSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VotesTable,
			Columns: []string{game.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVotesIDs(); len(nodes) > 0 && !_u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VotesTable,
			Columns: []string{game.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VotesTable,
			Columns: []string{game.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetStatus sets the "status" field.
func (_u *GameUpdateOne) SetStatus(v game.Status) *GameUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableStatus(v *game.Status) *GameUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *GameUpdateOne) SetPhase(v game.Phase) *GameUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillablePhase(v *game.Phase) *GameUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetRoundNumber sets the "round_number" field.
func (_u *GameUpdateOne) SetRoundNumber(v int) *GameUpdateOne {
	_u.mutation.ResetRoundNumber()
	_u.mutation.SetRoundNumber(v)
	return _u
}

// SetNillableRoundNumber sets the "round_number" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableRoundNumber(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetRoundNumber(*v)
	}
	return _u
}

// AddRoundNumber adds value to the "round_number" field.
func (_u *GameUpdateOne) AddRoundNumber(v int) *GameUpdateOne {
	_u.mutation.AddRoundNumber(v)
	return _u
}

// SetModeratorID sets the "moderator_id" field.
func (_u *GameUpdateOne) SetModeratorID(v string) *GameUpdateOne {
	_u.mutation.SetModeratorID(v)
	return _u
}

// SetNillableModeratorID sets the "moderator_id" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableModeratorID(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetModeratorID(*v)
	}
	return _u
}

// AddPlayerIDs adds the "players" edge to the Player entity by IDs.
func (_u *GameUpdateOne) AddPlayerIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the Player entity.
func (_u *GameUpdateOne) AddPlayers(v ...*Player) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// AddGameRoleIDs adds the "game_roles" edge to the GameRole entity by IDs.
func (_u *GameUpdateOne) AddGameRoleIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddGameRoleIDs(ids...)
	return _u
}

// AddGameRoles adds the "game_roles" edges to the GameRole entity.
func (_u *GameUpdateOne) AddGameRoles(v ...*GameRole) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGameRoleIDs(ids...)
}

// AddRoundIDs adds the "rounds" edge to the GameRound entity by IDs.
func (_u *GameUpdateOne) AddRoundIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.AddRoundIDs(ids...)
	return _u
}

// AddRounds adds the "rounds" edges to the GameRound entity.
func (_u *GameUpdateOne) AddRounds(v ...*GameRound) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoundIDs(ids...)
}

// AddEliminationIDs adds the "eliminations" edge to the Elimination entity by IDs.
func (_u *GameUpdateOne) AddEliminationIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.AddEliminationIDs(ids...)
	return _u
}

// AddEliminations adds the "eliminations" edges to the Elimination entity.
func (_u *GameUpdateOne) AddEliminations(v ...*Elimination) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEliminationIDs(ids...)
}

// AddVoteSessionIDs adds the "vote_sessions" edge to the VoteSession entity by IDs.
func (_u *GameUpdateOne) AddVoteSessionIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.AddVoteSessionIDs(ids...)
	return _u
}

// AddVoteSessions adds the "vote_sessions" edges to the VoteSession entity.
func (_u *GameUpdateOne) AddVoteSessions(v ...*VoteSession) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteSessionIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the Vote entity by IDs.
func (_u *GameUpdateOne) AddVoteIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.AddVoteIDs(ids...)
	return _u
}

// AddVotes adds the "votes" edges to the Vote entity.
func (_u *GameUpdateOne) AddVotes(v ...*Vote) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the Player entity.
func (_u *GameUpdateOne) ClearPlayers() *GameUpdateOne {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to Player entities by IDs.
func (_u *GameUpdateOne) RemovePlayerIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to Player entities.
func (_u *GameUpdateOne) RemovePlayers(v ...*Player) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearGameRoles clears all "game_roles" edges to the GameRole entity.
func (_u *GameUpdateOne) ClearGameRoles() *GameUpdateOne {
	_u.mutation.ClearGameRoles()
	return _u
}

// RemoveGameRoleIDs removes the "game_roles" edge to GameRole entities by IDs.
func (_u *GameUpdateOne) RemoveGameRoleIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemoveGameRoleIDs(ids...)
	return _u
}

// RemoveGameRoles removes "game_roles" edges to GameRole entities.
func (_u *GameUpdateOne) RemoveGameRoles(v ...*GameRole) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGameRoleIDs(ids...)
}

// ClearRounds clears all "rounds" edges to the GameRound entity.
func (_u *GameUpdateOne) ClearRounds() *GameUpdateOne {
	_u.mutation.ClearRounds()
	return _u
}

// RemoveRoundIDs removes the "rounds" edge to GameRound entities by IDs.
func (_u *GameUpdateOne) RemoveRoundIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.RemoveRoundIDs(ids...)
	return _u
}

// RemoveRounds removes "rounds" edges to GameRound entities.
func (_u *GameUpdateOne) RemoveRounds(v ...*GameRound) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoundIDs(ids...)
}

// ClearEliminations clears all "eliminations" edges to the Elimination entity.
func (_u *GameUpdateOne) ClearEliminations() *GameUpdateOne {
	_u.mutation.ClearEliminations()
	return _u
}

// RemoveEliminationIDs removes the "eliminations" edge to Elimination entities by IDs.
func (_u *GameUpdateOne) RemoveEliminationIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.RemoveEliminationIDs(ids...)
	return _u
}

// RemoveEliminations removes "eliminations" edges to Elimination entities.
func (_u *GameUpdateOne) RemoveEliminations(v ...*Elimination) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEliminationIDs(ids...)
}

// ClearVoteSessions clears all "vote_sessions" edges to the VoteSession entity.
func (_u *GameUpdateOne) ClearVoteSessions() *GameUpdateOne {
	_u.mutation.ClearVoteSessions()
	return _u
}

// RemoveVoteSessionIDs removes the "vote_sessions" edge to VoteSession entities by IDs.
func (_u *GameUpdateOne) RemoveVoteSessionIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.RemoveVoteSessionIDs(ids...)
	return _u
}

// RemoveVoteSessions removes "vote_sessions" edges to VoteSession entities.
func (_u *GameUpdateOne) RemoveVoteSessions(v ...*VoteSession) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteSessionIDs(ids...)
}

// ClearVotes clears all "votes" edges to the Vote entity.
func (_u *GameUpdateOne) ClearVotes() *GameUpdateOne {
	_u.mutation.ClearVotes()
	return _u
}

// RemoveVoteIDs removes the "votes" edge to Vote entities by IDs.
func (_u *GameUpdateOne) RemoveVoteIDs(ids ...uuid.UUID) *GameUpdateOne {
	_u.mutation.RemoveVoteIDs(ids...)
	return _u
}

// RemoveVotes removes "votes" edges to Vote entities.
func (_u *GameUpdateOne) RemoveVotes(v ...*Vote) *GameUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteIDs(ids...)
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := game.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Game.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := game.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Game.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoundNumber(); ok {
		if err := game.RoundNumberValidator(v); err != nil {
			return &ValidationError{Name: "round_number", err: fmt.Errorf(`ent: validator failed for field "Game.round_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModeratorID(); ok {
		if err := game.ModeratorIDValidator(v); err != nil {
			return &ValidationError{Name: "moderator_id", err: fmt.Errorf(`ent: validator failed for field "Game.moderator_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(game.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(game.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RoundNumber(); ok {
		_spec.SetField(game.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundNumber(); ok {
		_spec.AddField(game.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ModeratorID(); ok {
		_spec.SetField(game.FieldModeratorID, field.TypeString, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GameRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.GameRolesTable,
			Columns: []string{game.GameRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGameRolesIDs(); len(nodes) > 0 && !_u.mutation.GameRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.GameRolesTable,
			Columns: []string{game.GameRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.GameRolesTable,
			Columns: []string{game.GameRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamerole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.RoundsTable,
			Columns: []string{game.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoundsIDs(); len(nodes) > 0 && !_u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.RoundsTable,
			Columns: []string{game.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.RoundsTable,
			Columns: []string{game.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EliminationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.EliminationsTable,
			Columns: []string{game.EliminationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEliminationsIDs(); len(nodes) > 0 && !_u.mutation.EliminationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.EliminationsTable,
			Columns: []string{game.EliminationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EliminationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.EliminationsTable,
			Columns: []string{game.EliminationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elimination.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VoteSessionsTable,
			Columns: []string{game.VoteSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteSessionsIDs(); len(nodes) > 0 && !_u.mutation.VoteSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VoteSessionsTable,
			Columns: []string{game.VoteSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VoteSessionsTable,
			Columns: []string{game.VoteSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VotesTable,
			Columns: []string{game.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVotesIDs(); len(nodes) > 0 && !_u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VotesTable,
			Columns: []string{game.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.VotesTable,
			Columns: []string{game.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
