// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/roletemplate"
)

// RoleTemplate is the model entity for the RoleTemplate schema.
type RoleTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name of the role template
	Name string `json:"name,omitempty"`
	// Total number of players this template is designed for
	PlayerCount int `json:"player_count,omitempty"`
	// Description of the template and its gameplay style
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoleTemplateQuery when eager-loading is set.
	Edges        RoleTemplateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RoleTemplateEdges holds the relations/edges for other nodes in the graph.
type RoleTemplateEdges struct {
	// TemplateRoles holds the value of the template_roles edge.
	TemplateRoles []*RoleTemplateRole `json:"template_roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TemplateRolesOrErr returns the TemplateRoles value or an error if the edge
// was not loaded in eager-loading.
func (e RoleTemplateEdges) TemplateRolesOrErr() ([]*RoleTemplateRole, error) {
	if e.loadedTypes[0] {
		return e.TemplateRoles, nil
	}
	return nil, &NotLoadedError{edge: "template_roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoleTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case roletemplate.FieldPlayerCount:
			values[i] = new(sql.NullInt64)
		case roletemplate.FieldName, roletemplate.FieldDescription:
			values[i] = new(sql.NullString)
		case roletemplate.FieldCreatedAt, roletemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case roletemplate.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoleTemplate fields.
func (_m *RoleTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case roletemplate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case roletemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case roletemplate.FieldPlayerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field player_count", values[i])
			} else if value.Valid {
				_m.PlayerCount = int(value.Int64)
			}
		case roletemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case roletemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case roletemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoleTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *RoleTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTemplateRoles queries the "template_roles" edge of the RoleTemplate entity.
func (_m *RoleTemplate) QueryTemplateRoles() *RoleTemplateRoleQuery {
	return NewRoleTemplateClient(_m.config).QueryTemplateRoles(_m)
}

// Update returns a builder for updating this RoleTemplate.
// Note that you need to call RoleTemplate.Unwrap() before calling this method if this RoleTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoleTemplate) Update() *RoleTemplateUpdateOne {
	return NewRoleTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoleTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoleTemplate) Unwrap() *RoleTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoleTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoleTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("RoleTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("player_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlayerCount))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RoleTemplates is a parsable slice of RoleTemplate.
type RoleTemplates []*RoleTemplate
