// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/role"
	"github.com/mafia-night/backend/ent/roletemplate"
	"github.com/mafia-night/backend/ent/roletemplaterole"
)

// RoleTemplateRole is the model entity for the RoleTemplateRole schema.
type RoleTemplateRole struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Reference to the role template
	RoleTemplateID uuid.UUID `json:"role_template_id,omitempty"`
	// Reference to the role
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// Number of this role in the template
	Count int `json:"count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoleTemplateRoleQuery when eager-loading is set.
	Edges        RoleTemplateRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RoleTemplateRoleEdges holds the relations/edges for other nodes in the graph.
type RoleTemplateRoleEdges struct {
	// RoleTemplate holds the value of the role_template edge.
	RoleTemplate *RoleTemplate `json:"role_template,omitempty"`
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoleTemplateOrErr returns the RoleTemplate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoleTemplateRoleEdges) RoleTemplateOrErr() (*RoleTemplate, error) {
	if e.RoleTemplate != nil {
		return e.RoleTemplate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: roletemplate.Label}
	}
	return nil, &NotLoadedError{edge: "role_template"}
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoleTemplateRoleEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoleTemplateRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case roletemplaterole.FieldID, roletemplaterole.FieldCount:
			values[i] = new(sql.NullInt64)
		case roletemplaterole.FieldRoleTemplateID, roletemplaterole.FieldRoleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoleTemplateRole fields.
func (_m *RoleTemplateRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case roletemplaterole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case roletemplaterole.FieldRoleTemplateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_template_id", values[i])
			} else if value != nil {
				_m.RoleTemplateID = *value
			}
		case roletemplaterole.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case roletemplaterole.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoleTemplateRole.
// This includes values selected through modifiers, order, etc.
func (_m *RoleTemplateRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoleTemplate queries the "role_template" edge of the RoleTemplateRole entity.
func (_m *RoleTemplateRole) QueryRoleTemplate() *RoleTemplateQuery {
	return NewRoleTemplateRoleClient(_m.config).QueryRoleTemplate(_m)
}

// QueryRole queries the "role" edge of the RoleTemplateRole entity.
func (_m *RoleTemplateRole) QueryRole() *RoleQuery {
	return NewRoleTemplateRoleClient(_m.config).QueryRole(_m)
}

// Update returns a builder for updating this RoleTemplateRole.
// Note that you need to call RoleTemplateRole.Unwrap() before calling this method if this RoleTemplateRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoleTemplateRole) Update() *RoleTemplateRoleUpdateOne {
	return NewRoleTemplateRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoleTemplateRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoleTemplateRole) Unwrap() *RoleTemplateRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoleTemplateRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoleTemplateRole) String() string {
	var builder strings.Builder
	builder.WriteString("RoleTemplateRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role_template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleTemplateID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteByte(')')
	return builder.String()
}

// RoleTemplateRoles is a parsable slice of RoleTemplateRole.
type RoleTemplateRoles []*RoleTemplateRole
