// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/votesession"
)

// VoteSession is the model entity for the VoteSession schema.
type VoteSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID string `json:"game_id,omitempty"`
	// AccusedPlayerID holds the value of the "accused_player_id" field.
	AccusedPlayerID uuid.UUID `json:"accused_player_id,omitempty"`
	// AccusedPlayerName holds the value of the "accused_player_name" field.
	AccusedPlayerName string `json:"accused_player_name,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Status holds the value of the "status" field.
	Status votesession.Status `json:"status,omitempty"`
	// OpenedAt holds the value of the "opened_at" field.
	OpenedAt time.Time `json:"opened_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VoteSessionQuery when eager-loading is set.
	Edges        VoteSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VoteSessionEdges holds the relations/edges for other nodes in the graph.
type VoteSessionEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// Ballots holds the value of the ballots edge.
	Ballots []*Ballot `json:"ballots,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteSessionEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// BallotsOrErr returns the Ballots value or an error if the edge
// was not loaded in eager-loading.
func (e VoteSessionEdges) BallotsOrErr() ([]*Ballot, error) {
	if e.loadedTypes[1] {
		return e.Ballots, nil
	}
	return nil, &NotLoadedError{edge: "ballots"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VoteSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case votesession.FieldGameID, votesession.FieldAccusedPlayerName, votesession.FieldMessage, votesession.FieldStatus:
			values[i] = new(sql.NullString)
		case votesession.FieldOpenedAt, votesession.FieldClosedAt:
			values[i] = new(sql.NullTime)
		case votesession.FieldID, votesession.FieldAccusedPlayerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VoteSession fields.
func (_m *VoteSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case votesession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case votesession.FieldGameID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = value.String
			}
		case votesession.FieldAccusedPlayerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field accused_player_id", values[i])
			} else if value != nil {
				_m.AccusedPlayerID = *value
			}
		case votesession.FieldAccusedPlayerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field accused_player_name", values[i])
			} else if value.Valid {
				_m.AccusedPlayerName = value.String
			}
		case votesession.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case votesession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = votesession.Status(value.String)
			}
		case votesession.FieldOpenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opened_at", values[i])
			} else if value.Valid {
				_m.OpenedAt = value.Time
			}
		case votesession.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VoteSession.
// This includes values selected through modifiers, order, etc.
func (_m *VoteSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the VoteSession entity.
func (_m *VoteSession) QueryGame() *GameQuery {
	return NewVoteSessionClient(_m.config).QueryGame(_m)
}

// QueryBallots queries the "ballots" edge of the VoteSession entity.
func (_m *VoteSession) QueryBallots() *BallotQuery {
	return NewVoteSessionClient(_m.config).QueryBallots(_m)
}

// Update returns a builder for updating this VoteSession.
// Note that you need to call VoteSession.Unwrap() before calling this method if this VoteSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VoteSession) Update() *VoteSessionUpdateOne {
	return NewVoteSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VoteSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VoteSession) Unwrap() *VoteSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VoteSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VoteSession) String() string {
	var builder strings.Builder
	builder.WriteString("VoteSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("game_id=")
	builder.WriteString(_m.GameID)
	builder.WriteString(", ")
	builder.WriteString("accused_player_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccusedPlayerID))
	builder.WriteString(", ")
	builder.WriteString("accused_player_name=")
	builder.WriteString(_m.AccusedPlayerName)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("opened_at=")
	builder.WriteString(_m.OpenedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// VoteSessions is a parsable slice of VoteSession.
type VoteSessions []*VoteSession
