// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/gameround"
	"github.com/mafia-night/backend/ent/player"
	"github.com/mafia-night/backend/ent/predicate"
	"github.com/mafia-night/backend/ent/vote"
)

// VoteUpdate is the builder for updating Vote entities.
type VoteUpdate struct {
	config
	hooks    []Hook
	mutation *VoteMutation
}

// Where appends a list predicates to the VoteUpdate builder.
func (_u *VoteUpdate) Where(ps ...predicate.Vote) *VoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *VoteUpdate) SetGameID(v string) *VoteUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *VoteUpdate) SetNillableGameID(v *string) *VoteUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRoundID sets the "round_id" field.
func (_u *VoteUpdate) SetRoundID(v uuid.UUID) *VoteUpdate {
	_u.mutation.SetRoundID(v)
	return _u
}

// SetNillableRoundID sets the "round_id" field if the given value is not nil.
func (_u *VoteUpdate) SetNillableRoundID(v *uuid.UUID) *VoteUpdate {
	if v != nil {
		_u.SetRoundID(*v)
	}
	return _u
}

// SetVoterID sets the "voter_id" field.
func (_u *VoteUpdate) SetVoterID(v uuid.UUID) *VoteUpdate {
	_u.mutation.SetVoterID(v)
	return _u
}

// SetNillableVoterID sets the "voter_id" field if the given value is not nil.
func (_u *VoteUpdate) SetNillableVoterID(v *uuid.UUID) *VoteUpdate {
	if v != nil {
		_u.SetVoterID(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *VoteUpdate) SetTargetID(v uuid.UUID) *VoteUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *VoteUpdate) SetNillableTargetID(v *uuid.UUID) *VoteUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *VoteUpdate) SetStage(v vote.Stage) *VoteUpdate {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *VoteUpdate) SetNillableStage(v *vote.Stage) *VoteUpdate {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *VoteUpdate) SetGame(v *Game) *VoteUpdate {
	return _u.SetGameID(v.ID)
}

// SetRound sets the "round" edge to the GameRound entity.
func (_u *VoteUpdate) SetRound(v *GameRound) *VoteUpdate {
	return _u.SetRoundID(v.ID)
}

// SetVoter sets the "voter" edge to the Player entity.
func (_u *VoteUpdate) SetVoter(v *Player) *VoteUpdate {
	return _u.SetVoterID(v.ID)
}

// SetTarget sets the "target" edge to the Player entity.
func (_u *VoteUpdate) SetTarget(v *Player) *VoteUpdate {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the VoteMutation object of the builder.
func (_u *VoteUpdate) Mutation() *VoteMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *VoteUpdate) ClearGame() *VoteUpdate {
	_u.mutation.ClearGame()
	return _u
}

// ClearRound clears the "round" edge to the GameRound entity.
func (_u *VoteUpdate) ClearRound() *VoteUpdate {
	_u.mutation.ClearRound()
	return _u
}

// ClearVoter clears the "voter" edge to the Player entity.
func (_u *VoteUpdate) ClearVoter() *VoteUpdate {
	_u.mutation.ClearVoter()
	return _u
}

// ClearTarget clears the "target" edge to the Player entity.
func (_u *VoteUpdate) ClearTarget() *VoteUpdate {
	_u.mutation.ClearTarget()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoteUpdate) check() error {
	if v, ok := _u.mutation.GameID(); ok {
		if err := vote.GameIDValidator(v); err != nil {
			return &ValidationError{Name: "game_id", err: fmt.Errorf(`ent: validator failed for field "Vote.game_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stage(); ok {
		if err := vote.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "Vote.stage": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.game"`)
	}
	if _u.mutation.RoundCleared() && len(_u.mutation.RoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.round"`)
	}
	if _u.mutation.VoterCleared() && len(_u.mutation.VoterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.voter"`)
	}
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.target"`)
	}
	return nil
}

func (_u *VoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vote.Table, vote.Columns, sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(vote.FieldStage, field.TypeEnum, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.GameTable,
			Columns: []string{vote.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.GameTable,
			Columns: []string{vote.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.RoundTable,
			Columns: []string{vote.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.RoundTable,
			Columns: []string{vote.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.VoterTable,
			Columns: []string{vote.VoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.VoterTable,
			Columns: []string{vote.VoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.TargetTable,
			Columns: []string{vote.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.TargetTable,
			Columns: []string{vote.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VoteUpdateOne is the builder for updating a single Vote entity.
type VoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoteMutation
}

// SetGameID sets the "game_id" field.
func (_u *VoteUpdateOne) SetGameID(v string) *VoteUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *VoteUpdateOne) SetNillableGameID(v *string) *VoteUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRoundID sets the "round_id" field.
func (_u *VoteUpdateOne) SetRoundID(v uuid.UUID) *VoteUpdateOne {
	_u.mutation.SetRoundID(v)
	return _u
}

// SetNillableRoundID sets the "round_id" field if the given value is not nil.
func (_u *VoteUpdateOne) SetNillableRoundID(v *uuid.UUID) *VoteUpdateOne {
	if v != nil {
		_u.SetRoundID(*v)
	}
	return _u
}

// SetVoterID sets the "voter_id" field.
func (_u *VoteUpdateOne) SetVoterID(v uuid.UUID) *VoteUpdateOne {
	_u.mutation.SetVoterID(v)
	return _u
}

// SetNillableVoterID sets the "voter_id" field if the given value is not nil.
func (_u *VoteUpdateOne) SetNillableVoterID(v *uuid.UUID) *VoteUpdateOne {
	if v != nil {
		_u.SetVoterID(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *VoteUpdateOne) SetTargetID(v uuid.UUID) *VoteUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *VoteUpdateOne) SetNillableTargetID(v *uuid.UUID) *VoteUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *VoteUpdateOne) SetStage(v vote.Stage) *VoteUpdateOne {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *VoteUpdateOne) SetNillableStage(v *vote.Stage) *VoteUpdateOne {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *VoteUpdateOne) SetGame(v *Game) *VoteUpdateOne {
	return _u.SetGameID(v.ID)
}

// SetRound sets the "round" edge to the GameRound entity.
func (_u *VoteUpdateOne) SetRound(v *GameRound) *VoteUpdateOne {
	return _u.SetRoundID(v.ID)
}

// SetVoter sets the "voter" edge to the Player entity.
func (_u *VoteUpdateOne) SetVoter(v *Player) *VoteUpdateOne {
	return _u.SetVoterID(v.ID)
}

// SetTarget sets the "target" edge to the Player entity.
func (_u *VoteUpdateOne) SetTarget(v *Player) *VoteUpdateOne {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the VoteMutation object of the builder.
func (_u *VoteUpdateOne) Mutation() *VoteMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *VoteUpdateOne) ClearGame() *VoteUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// ClearRound clears the "round" edge to the GameRound entity.
func (_u *VoteUpdateOne) ClearRound() *VoteUpdateOne {
	_u.mutation.ClearRound()
	return _u
}

// ClearVoter clears the "voter" edge to the Player entity.
func (_u *VoteUpdateOne) ClearVoter() *VoteUpdateOne {
	_u.mutation.ClearVoter()
	return _u
}

// ClearTarget clears the "target" edge to the Player entity.
func (_u *VoteUpdateOne) ClearTarget() *VoteUpdateOne {
	_u.mutation.ClearTarget()
	return _u
}

// Where appends a list predicates to the VoteUpdate builder.
func (_u *VoteUpdateOne) Where(ps ...predicate.Vote) *VoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VoteUpdateOne) Select(field string, fields ...string) *VoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Vote entity.
func (_u *VoteUpdateOne) Save(ctx context.Context) (*Vote, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoteUpdateOne) SaveX(ctx context.Context) *Vote {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoteUpdateOne) check() error {
	if v, ok := _u.mutation.GameID(); ok {
		if err := vote.GameIDValidator(v); err != nil {
			return &ValidationError{Name: "game_id", err: fmt.Errorf(`ent: validator failed for field "Vote.game_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stage(); ok {
		if err := vote.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "Vote.stage": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.game"`)
	}
	if _u.mutation.RoundCleared() && len(_u.mutation.RoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.round"`)
	}
	if _u.mutation.VoterCleared() && len(_u.mutation.VoterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.voter"`)
	}
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.target"`)
	}
	return nil
}

func (_u *VoteUpdateOne) sqlSave(ctx context.Context) (_node *Vote, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vote.Table, vote.Columns, sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Vote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vote.FieldID)
		for _, f := range fields {
			if !vote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(vote.FieldStage, field.TypeEnum, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.GameTable,
			Columns: []string{vote.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.GameTable,
			Columns: []string{vote.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.RoundTable,
			Columns: []string{vote.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.RoundTable,
			Columns: []string{vote.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameround.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.VoterTable,
			Columns: []string{vote.VoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.VoterTable,
			Columns: []string{vote.VoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.TargetTable,
			Columns: []string{vote.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vote.TargetTable,
			Columns: []string{vote.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Vote{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
