// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/ballot"
	"github.com/mafia-night/backend/ent/game"
	"github.com/mafia-night/backend/ent/predicate"
	"github.com/mafia-night/backend/ent/votesession"
)

// VoteSessionQuery is the builder for querying VoteSession entities.
type VoteSessionQuery struct {
	config
	ctx         *QueryContext
	order       []votesession.OrderOption
	inters      []Interceptor
	predicates  []predicate.VoteSession
	withGame    *GameQuery
	withBallots *BallotQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoteSessionQuery builder.
func (_q *VoteSessionQuery) Where(ps ...predicate.VoteSession) *VoteSessionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VoteSessionQuery) Limit(limit int) *VoteSessionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VoteSessionQuery) Offset(offset int) *VoteSessionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VoteSessionQuery) Unique(unique bool) *VoteSessionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VoteSessionQuery) Order(o ...votesession.OrderOption) *VoteSessionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGame chains the current query on the "game" edge.
func (_q *VoteSessionQuery) QueryGame() *GameQuery {
	query := (&GameClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(votesession.Table, votesession.FieldID, selector),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, votesession.GameTable, votesession.GameColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBallots chains the current query on the "ballots" edge.
func (_q *VoteSessionQuery) QueryBallots() *BallotQuery {
	query := (&BallotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(votesession.Table, votesession.FieldID, selector),
			sqlgraph.To(ballot.Table, ballot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, votesession.BallotsTable, votesession.BallotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VoteSession entity from the query.
// Returns a *NotFoundError when no VoteSession was found.
func (_q *VoteSessionQuery) First(ctx context.Context) (*VoteSession, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{votesession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VoteSessionQuery) FirstX(ctx context.Context) *VoteSession {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VoteSession ID from the query.
// Returns a *NotFoundError when no VoteSession ID was found.
func (_q *VoteSessionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{votesession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VoteSessionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VoteSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VoteSession entity is found.
// Returns a *NotFoundError when no VoteSession entities are found.
func (_q *VoteSessionQuery) Only(ctx context.Context) (*VoteSession, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{votesession.Label}
	default:
		return nil, &NotSingularError{votesession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VoteSessionQuery) OnlyX(ctx context.Context) *VoteSession {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VoteSession ID in the query.
// Returns a *NotSingularError when more than one VoteSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VoteSessionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{votesession.Label}
	default:
		err = &NotSingularError{votesession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VoteSessionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VoteSessions.
func (_q *VoteSessionQuery) All(ctx context.Context) ([]*VoteSession, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VoteSession, *VoteSessionQuery]()
	return withInterceptors[[]*VoteSession](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VoteSessionQuery) AllX(ctx context.Context) []*VoteSession {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VoteSession IDs.
func (_q *VoteSessionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(votesession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VoteSessionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VoteSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VoteSessionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VoteSessionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VoteSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VoteSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoteSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VoteSessionQuery) Clone() *VoteSessionQuery {
	if _q == nil {
		return nil
	}
	return &VoteSessionQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]votesession.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.VoteSession{}, _q.predicates...),
		withGame:    _q.withGame.Clone(),
		withBallots: _q.withBallots.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGame tells the query-builder to eager-load the nodes that are connected to
// the "game" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VoteSessionQuery) WithGame(opts ...func(*GameQuery)) *VoteSessionQuery {
	query := (&GameClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGame = query
	return _q
}

// WithBallots tells the query-builder to eager-load the nodes that are connected to
// the "ballots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VoteSessionQuery) WithBallots(opts ...func(*BallotQuery)) *VoteSessionQuery {
	query := (&BallotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBallots = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GameID string `json:"game_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VoteSession.Query().
//		GroupBy(votesession.FieldGameID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VoteSessionQuery) GroupBy(field string, fields ...string) *VoteSessionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VoteSessionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = votesession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GameID string `json:"game_id,omitempty"`
//	}
//
//	client.VoteSession.Query().
//		Select(votesession.FieldGameID).
//		Scan(ctx, &v)
func (_q *VoteSessionQuery) Select(fields ...string) *VoteSessionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VoteSessionSelect{VoteSessionQuery: _q}
	sbuild.label = votesession.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VoteSessionSelect configured with the given aggregations.
func (_q *VoteSessionQuery) Aggregate(fns ...AggregateFunc) *VoteSessionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VoteSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !votesession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VoteSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VoteSession, error) {
	var (
		nodes       = []*VoteSession{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withGame != nil,
			_q.withBallots != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VoteSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VoteSession{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGame; query != nil {
		if err := _q.loadGame(ctx, query, nodes, nil,
			func(n *VoteSession, e *Game) { n.Edges.Game = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBallots; query != nil {
		if err := _q.loadBallots(ctx, query, nodes,
			func(n *VoteSession) { n.Edges.Ballots = []*Ballot{} },
			func(n *VoteSession, e *Ballot) { n.Edges.Ballots = append(n.Edges.Ballots, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VoteSessionQuery) loadGame(ctx context.Context, query *GameQuery, nodes []*VoteSession, init func(*VoteSession), assign func(*VoteSession, *Game)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*VoteSession)
	for i := range nodes {
		fk := nodes[i].GameID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(game.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VoteSessionQuery) loadBallots(ctx context.Context, query *BallotQuery, nodes []*VoteSession, init func(*VoteSession), assign func(*VoteSession, *Ballot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*VoteSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ballot.FieldSessionID)
	}
	query.Where(predicate.Ballot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(votesession.BallotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *VoteSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VoteSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(votesession.Table, votesession.Columns, sqlgraph.NewFieldSpec(votesession.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, votesession.FieldID)
		for i := range fields {
			if fields[i] != votesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGame != nil {
			_spec.Node.AddColumnOnce(votesession.FieldGameID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VoteSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(votesession.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = votesession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VoteSessionGroupBy is the group-by builder for VoteSession entities.
type VoteSessionGroupBy struct {
	selector
	build *VoteSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VoteSessionGroupBy) Aggregate(fns ...AggregateFunc) *VoteSessionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VoteSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoteSessionQuery, *VoteSessionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VoteSessionGroupBy) sqlScan(ctx context.Context, root *VoteSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VoteSessionSelect is the builder for selecting fields of VoteSession entities.
type VoteSessionSelect struct {
	*VoteSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VoteSessionSelect) Aggregate(fns ...AggregateFunc) *VoteSessionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VoteSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoteSessionQuery, *VoteSessionSelect](ctx, _s.VoteSessionQuery, _s, _s.inters, v)
}

func (_s *VoteSessionSelect) sqlScan(ctx context.Context, root *VoteSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
