// Code generated by ent, DO NOT EDIT.

package gameround

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GameRound {
	return predicate.GameRound(sql.FieldLTE(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldGameID, v))
}

// RoundNumber applies equality check predicate on the "round_number" field. It's identical to RoundNumberEQ.
func RoundNumber(v int) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldRoundNumber, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldEndedAt, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...string) predicate.GameRound {
	return predicate.GameRound(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...string) predicate.GameRound {
	return predicate.GameRound(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldLTE(FieldGameID, v))
}

// GameIDContains applies the Contains predicate on the "game_id" field.
func GameIDContains(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldContains(FieldGameID, v))
}

// GameIDHasPrefix applies the HasPrefix predicate on the "game_id" field.
func GameIDHasPrefix(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldHasPrefix(FieldGameID, v))
}

// GameIDHasSuffix applies the HasSuffix predicate on the "game_id" field.
func GameIDHasSuffix(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldHasSuffix(FieldGameID, v))
}

// GameIDEqualFold applies the EqualFold predicate on the "game_id" field.
func GameIDEqualFold(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldEqualFold(FieldGameID, v))
}

// GameIDContainsFold applies the ContainsFold predicate on the "game_id" field.
func GameIDContainsFold(v string) predicate.GameRound {
	return predicate.GameRound(sql.FieldContainsFold(FieldGameID, v))
}

// RoundNumberEQ applies the EQ predicate on the "round_number" field.
func RoundNumberEQ(v int) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldRoundNumber, v))
}

// RoundNumberNEQ applies the NEQ predicate on the "round_number" field.
func RoundNumberNEQ(v int) predicate.GameRound {
	return predicate.GameRound(sql.FieldNEQ(FieldRoundNumber, v))
}

// RoundNumberIn applies the In predicate on the "round_number" field.
func RoundNumberIn(vs ...int) predicate.GameRound {
	return predicate.GameRound(sql.FieldIn(FieldRoundNumber, vs...))
}

// RoundNumberNotIn applies the NotIn predicate on the "round_number" field.
func RoundNumberNotIn(vs ...int) predicate.GameRound {
	return predicate.GameRound(sql.FieldNotIn(FieldRoundNumber, vs...))
}

// RoundNumberGT applies the GT predicate on the "round_number" field.
func RoundNumberGT(v int) predicate.GameRound {
	return predicate.GameRound(sql.FieldGT(FieldRoundNumber, v))
}

// RoundNumberGTE applies the GTE predicate on the "round_number" field.
func RoundNumberGTE(v int) predicate.GameRound {
	return predicate.GameRound(sql.FieldGTE(FieldRoundNumber, v))
}

// RoundNumberLT applies the LT predicate on the "round_number" field.
func RoundNumberLT(v int) predicate.GameRound {
	return predicate.GameRound(sql.FieldLT(FieldRoundNumber, v))
}

// RoundNumberLTE applies the LTE predicate on the "round_number" field.
func RoundNumberLTE(v int) predicate.GameRound {
	return predicate.GameRound(sql.FieldLTE(FieldRoundNumber, v))
}

// PhaseEQ applies the EQ predicate on the "phase" field.
func PhaseEQ(v Phase) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldPhase, v))
}

// PhaseNEQ applies the NEQ predicate on the "phase" field.
func PhaseNEQ(v Phase) predicate.GameRound {
	return predicate.GameRound(sql.FieldNEQ(FieldPhase, v))
}

// PhaseIn applies the In predicate on the "phase" field.
func PhaseIn(vs ...Phase) predicate.GameRound {
	return predicate.GameRound(sql.FieldIn(FieldPhase, vs...))
}

// PhaseNotIn applies the NotIn predicate on the "phase" field.
func PhaseNotIn(vs ...Phase) predicate.GameRound {
	return predicate.GameRound(sql.FieldNotIn(FieldPhase, vs...))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.GameRound {
	return predicate.GameRound(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.GameRound {
	return predicate.GameRound(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.GameRound {
	return predicate.GameRound(sql.FieldNotNull(FieldEndedAt))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.GameRound {
	return predicate.GameRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.GameRound {
	return predicate.GameRound(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEliminations applies the HasEdge predicate on the "eliminations" edge.
func HasEliminations() predicate.GameRound {
	return predicate.GameRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EliminationsTable, EliminationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEliminationsWith applies the HasEdge predicate on the "eliminations" edge with a given conditions (other predicates).
func HasEliminationsWith(preds ...predicate.Elimination) predicate.GameRound {
	return predicate.GameRound(func(s *sql.Selector) {
		step := newEliminationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVotes applies the HasEdge predicate on the "votes" edge.
func HasVotes() predicate.GameRound {
	return predicate.GameRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VotesTable, VotesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVotesWith applies the HasEdge predicate on the "votes" edge with a given conditions (other predicates).
func HasVotesWith(preds ...predicate.Vote) predicate.GameRound {
	return predicate.GameRound(func(s *sql.Selector) {
		step := newVotesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameRound) predicate.GameRound {
	return predicate.GameRound(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameRound) predicate.GameRound {
	return predicate.GameRound(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameRound) predicate.GameRound {
	return predicate.GameRound(sql.NotPredicates(p))
}
