// Code generated by ent, DO NOT EDIT.

package ballot

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ballot type in the database.
	Label = "ballot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldVoterID holds the string denoting the voter_id field in the database.
	FieldVoterID = "voter_id"
	// FieldChoice holds the string denoting the choice field in the database.
	FieldChoice = "choice"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// Table holds the table name of the ballot in the database.
	Table = "ballots"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "ballots"
	// SessionInverseTable is the table name for the VoteSession entity.
	// It exists in this package in order to avoid circular dependency with the "votesession" package.
	SessionInverseTable = "vote_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
)

// Columns holds all SQL columns for ballot fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldVoterID,
	FieldChoice,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Choice defines the type for the "choice" enum field.
type Choice string

// Choice values.
const (
	ChoiceYes Choice = "yes"
	ChoiceNo  Choice = "no"
)

func (c Choice) String() string {
	return string(c)
}

// ChoiceValidator is a validator for the "choice" field enum values. It is called by the builders before save.
func ChoiceValidator(c Choice) error {
	switch c {
	case ChoiceYes, ChoiceNo:
		return nil
	default:
		return fmt.Errorf("ballot: invalid enum value for choice field: %q", c)
	}
}

// OrderOption defines the ordering options for the Ballot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByVoterID orders the results by the voter_id field.
func ByVoterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoterID, opts...).ToFunc()
}

// ByChoice orders the results by the choice field.
func ByChoice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChoice, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
