// Code generated by ent, DO NOT EDIT.

package ballot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldSessionID, v))
}

// VoterID applies equality check predicate on the "voter_id" field. It's identical to VoterIDEQ.
func VoterID(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldVoterID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldCreatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldNotIn(FieldSessionID, vs...))
}

// VoterIDEQ applies the EQ predicate on the "voter_id" field.
func VoterIDEQ(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldVoterID, v))
}

// VoterIDNEQ applies the NEQ predicate on the "voter_id" field.
func VoterIDNEQ(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldNEQ(FieldVoterID, v))
}

// VoterIDIn applies the In predicate on the "voter_id" field.
func VoterIDIn(vs ...uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldIn(FieldVoterID, vs...))
}

// VoterIDNotIn applies the NotIn predicate on the "voter_id" field.
func VoterIDNotIn(vs ...uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldNotIn(FieldVoterID, vs...))
}

// VoterIDGT applies the GT predicate on the "voter_id" field.
func VoterIDGT(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldGT(FieldVoterID, v))
}

// VoterIDGTE applies the GTE predicate on the "voter_id" field.
func VoterIDGTE(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldGTE(FieldVoterID, v))
}

// VoterIDLT applies the LT predicate on the "voter_id" field.
func VoterIDLT(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldLT(FieldVoterID, v))
}

// VoterIDLTE applies the LTE predicate on the "voter_id" field.
func VoterIDLTE(v uuid.UUID) predicate.Ballot {
	return predicate.Ballot(sql.FieldLTE(FieldVoterID, v))
}

// ChoiceEQ applies the EQ predicate on the "choice" field.
func ChoiceEQ(v Choice) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldChoice, v))
}

// ChoiceNEQ applies the NEQ predicate on the "choice" field.
func ChoiceNEQ(v Choice) predicate.Ballot {
	return predicate.Ballot(sql.FieldNEQ(FieldChoice, v))
}

// ChoiceIn applies the In predicate on the "choice" field.
func ChoiceIn(vs ...Choice) predicate.Ballot {
	return predicate.Ballot(sql.FieldIn(FieldChoice, vs...))
}

// ChoiceNotIn applies the NotIn predicate on the "choice" field.
func ChoiceNotIn(vs ...Choice) predicate.Ballot {
	return predicate.Ballot(sql.FieldNotIn(FieldChoice, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Ballot {
	return predicate.Ballot(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.Ballot {
	return predicate.Ballot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.VoteSession) predicate.Ballot {
	return predicate.Ballot(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ballot) predicate.Ballot {
	return predicate.Ballot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ballot) predicate.Ballot {
	return predicate.Ballot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ballot) predicate.Ballot {
	return predicate.Ballot(sql.NotPredicates(p))
}
