// Code generated by ent, DO NOT EDIT.

package roletemplaterole

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldLTE(FieldID, id))
}

// RoleTemplateID applies equality check predicate on the "role_template_id" field. It's identical to RoleTemplateIDEQ.
func RoleTemplateID(v uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldRoleTemplateID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldRoleID, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldCount, v))
}

// RoleTemplateIDEQ applies the EQ predicate on the "role_template_id" field.
func RoleTemplateIDEQ(v uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldRoleTemplateID, v))
}

// RoleTemplateIDNEQ applies the NEQ predicate on the "role_template_id" field.
func RoleTemplateIDNEQ(v uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNEQ(FieldRoleTemplateID, v))
}

// RoleTemplateIDIn applies the In predicate on the "role_template_id" field.
func RoleTemplateIDIn(vs ...uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldIn(FieldRoleTemplateID, vs...))
}

// RoleTemplateIDNotIn applies the NotIn predicate on the "role_template_id" field.
func RoleTemplateIDNotIn(vs ...uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNotIn(FieldRoleTemplateID, vs...))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNotIn(FieldRoleID, vs...))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.FieldLTE(FieldCount, v))
}

// HasRoleTemplate applies the HasEdge predicate on the "role_template" edge.
func HasRoleTemplate() predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoleTemplateTable, RoleTemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleTemplateWith applies the HasEdge predicate on the "role_template" edge with a given conditions (other predicates).
func HasRoleTemplateWith(preds ...predicate.RoleTemplate) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(func(s *sql.Selector) {
		step := newRoleTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoleTemplateRole) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoleTemplateRole) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoleTemplateRole) predicate.RoleTemplateRole {
	return predicate.RoleTemplateRole(sql.NotPredicates(p))
}
