// Code generated by ent, DO NOT EDIT.

package elimination

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mafia-night/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldLTE(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldGameID, v))
}

// RoundID applies equality check predicate on the "round_id" field. It's identical to RoundIDEQ.
func RoundID(v uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldRoundID, v))
}

// PlayerID applies equality check predicate on the "player_id" field. It's identical to PlayerIDEQ.
func PlayerID(v uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldPlayerID, v))
}

// EliminatedAt applies equality check predicate on the "eliminated_at" field. It's identical to EliminatedAtEQ.
func EliminatedAt(v time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldEliminatedAt, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...string) predicate.Elimination {
	return predicate.Elimination(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...string) predicate.Elimination {
	return predicate.Elimination(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldLTE(FieldGameID, v))
}

// GameIDContains applies the Contains predicate on the "game_id" field.
func GameIDContains(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldContains(FieldGameID, v))
}

// GameIDHasPrefix applies the HasPrefix predicate on the "game_id" field.
func GameIDHasPrefix(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldHasPrefix(FieldGameID, v))
}

// GameIDHasSuffix applies the HasSuffix predicate on the "game_id" field.
func GameIDHasSuffix(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldHasSuffix(FieldGameID, v))
}

// GameIDEqualFold applies the EqualFold predicate on the "game_id" field.
func GameIDEqualFold(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldEqualFold(FieldGameID, v))
}

// GameIDContainsFold applies the ContainsFold predicate on the "game_id" field.
func GameIDContainsFold(v string) predicate.Elimination {
	return predicate.Elimination(sql.FieldContainsFold(FieldGameID, v))
}

// RoundIDEQ applies the EQ predicate on the "round_id" field.
func RoundIDEQ(v uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldRoundID, v))
}

// RoundIDNEQ applies the NEQ predicate on the "round_id" field.
func RoundIDNEQ(v uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldNEQ(FieldRoundID, v))
}

// RoundIDIn applies the In predicate on the "round_id" field.
func RoundIDIn(vs ...uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldIn(FieldRoundID, vs...))
}

// RoundIDNotIn applies the NotIn predicate on the "round_id" field.
func RoundIDNotIn(vs ...uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldNotIn(FieldRoundID, vs...))
}

// RoundIDIsNil applies the IsNil predicate on the "round_id" field.
func RoundIDIsNil() predicate.Elimination {
	return predicate.Elimination(sql.FieldIsNull(FieldRoundID))
}

// RoundIDNotNil applies the NotNil predicate on the "round_id" field.
func RoundIDNotNil() predicate.Elimination {
	return predicate.Elimination(sql.FieldNotNull(FieldRoundID))
}

// PlayerIDEQ applies the EQ predicate on the "player_id" field.
func PlayerIDEQ(v uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldPlayerID, v))
}

// PlayerIDNEQ applies the NEQ predicate on the "player_id" field.
func PlayerIDNEQ(v uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldNEQ(FieldPlayerID, v))
}

// PlayerIDIn applies the In predicate on the "player_id" field.
func PlayerIDIn(vs ...uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldIn(FieldPlayerID, vs...))
}

// PlayerIDNotIn applies the NotIn predicate on the "player_id" field.
func PlayerIDNotIn(vs ...uuid.UUID) predicate.Elimination {
	return predicate.Elimination(sql.FieldNotIn(FieldPlayerID, vs...))
}

// CauseEQ applies the EQ predicate on the "cause" field.
func CauseEQ(v Cause) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldCause, v))
}

// CauseNEQ applies the NEQ predicate on the "cause" field.
func CauseNEQ(v Cause) predicate.Elimination {
	return predicate.Elimination(sql.FieldNEQ(FieldCause, v))
}

// CauseIn applies the In predicate on the "cause" field.
func CauseIn(vs ...Cause) predicate.Elimination {
	return predicate.Elimination(sql.FieldIn(FieldCause, vs...))
}

// CauseNotIn applies the NotIn predicate on the "cause" field.
func CauseNotIn(vs ...Cause) predicate.Elimination {
	return predicate.Elimination(sql.FieldNotIn(FieldCause, vs...))
}

// EliminatedAtEQ applies the EQ predicate on the "eliminated_at" field.
func EliminatedAtEQ(v time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldEQ(FieldEliminatedAt, v))
}

// EliminatedAtNEQ applies the NEQ predicate on the "eliminated_at" field.
func EliminatedAtNEQ(v time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldNEQ(FieldEliminatedAt, v))
}

// EliminatedAtIn applies the In predicate on the "eliminated_at" field.
func EliminatedAtIn(vs ...time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldIn(FieldEliminatedAt, vs...))
}

// EliminatedAtNotIn applies the NotIn predicate on the "eliminated_at" field.
func EliminatedAtNotIn(vs ...time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldNotIn(FieldEliminatedAt, vs...))
}

// EliminatedAtGT applies the GT predicate on the "eliminated_at" field.
func EliminatedAtGT(v time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldGT(FieldEliminatedAt, v))
}

// EliminatedAtGTE applies the GTE predicate on the "eliminated_at" field.
func EliminatedAtGTE(v time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldGTE(FieldEliminatedAt, v))
}

// EliminatedAtLT applies the LT predicate on the "eliminated_at" field.
func EliminatedAtLT(v time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldLT(FieldEliminatedAt, v))
}

// EliminatedAtLTE applies the LTE predicate on the "eliminated_at" field.
func EliminatedAtLTE(v time.Time) predicate.Elimination {
	return predicate.Elimination(sql.FieldLTE(FieldEliminatedAt, v))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.Elimination {
	return predicate.Elimination(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.Elimination {
	return predicate.Elimination(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRound applies the HasEdge predicate on the "round" edge.
func HasRound() predicate.Elimination {
	return predicate.Elimination(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoundTable, RoundColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoundWith applies the HasEdge predicate on the "round" edge with a given conditions (other predicates).
func HasRoundWith(preds ...predicate.GameRound) predicate.Elimination {
	return predicate.Elimination(func(s *sql.Selector) {
		step := newRoundStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlayer applies the HasEdge predicate on the "player" edge.
func HasPlayer() predicate.Elimination {
	return predicate.Elimination(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerWith applies the HasEdge predicate on the "player" edge with a given conditions (other predicates).
func HasPlayerWith(preds ...predicate.Player) predicate.Elimination {
	return predicate.Elimination(func(s *sql.Selector) {
		step := newPlayerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Elimination) predicate.Elimination {
	return predicate.Elimination(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Elimination) predicate.Elimination {
	return predicate.Elimination(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Elimination) predicate.Elimination {
	return predicate.Elimination(sql.NotPredicates(p))
}
